# AMIT Final Project

In [131]:
import numpy as np
import pandas as pd
import re

In [132]:
df= pd.read_csv(r"C:\Users\mohsa\OneDrive\Desktop\AMIT Final Project\phone search (1) (4).csv")
df.shape

(340, 20)

In [133]:
df.head()

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.00,$169.99,USD,4.0,1319,16,$69.88,False,False,True,Only 1 left in stock - order soon.,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$153.99,NaN,USD,4.2,186,4,$147.50,False,False,True,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",$69.00,$99.99,USD,3.8,597,35,$64.99,False,False,True,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.99,NaN,USD,4.2,2814,3,$43.99,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",$88.09,$98.27,USD,3.8,1338,31,$70.40,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_title                340 non-null    object
 2   product_price                336 non-null    object
 3   product_original_price       148 non-null    object
 4   currency                     336 non-null    object
 5   product_star_rating          337 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  336 non-null    object
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         75 non-null     object
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 320 non-null    object
 15  delivery                     337 non-null    object
 16  has_variations               340 non-null    bool
 17  unit_price                   4 non-null      object
 18  unit_count                   4 non-null      float64
 19  coupon_text                  22 non-null     object
dtypes: bool(5), float64(2), int64(2), object(11)
memory usage: 41.6+ KB

In [135]:
df.head()

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.00,$169.99,USD,4.0,1319,16,$69.88,False,False,True,Only 1 left in stock - order soon.,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",$153.99,NaN,USD,4.2,186,4,$147.50,False,False,True,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",$69.00,$99.99,USD,3.8,597,35,$64.99,False,False,True,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,$49.99,NaN,USD,4.2,2814,3,$43.99,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",$88.09,$98.27,USD,3.8,1338,31,$70.40,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN

In [136]:
df.columns

Index(['asin', 'product_title', 'product_price', 'product_original_price',
       'currency', 'product_star_rating', 'product_num_ratings',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'product_availability',
       'climate_pledge_friendly', 'sales_volume', 'delivery', 'has_variations',
       'unit_price', 'unit_count', 'coupon_text'],
      dtype='object')

Data cleaning for the Prices columns

In [137]:
# cahnging the data type of the column to float
df['product_original_price'] = df['product_original_price'].str.replace('$', '') ## Still string
df['product_original_price'] = df['product_original_price'].str.replace(',', '') ## Clear numbers but still string
df['product_original_price'] = df['product_original_price'].astype(float) ## Converted to float

In [138]:
# cahnging the data type of the column to float
df['product_price'] = df['product_price'].str.replace('$', '') ## Still string
df['product_price'] = df['product_price'].str.replace(',', '') ## Clear numbers but still string
df['product_price'] = df['product_price'].astype(float) ## Converted to float

In [139]:
# cahnging the data type of the column to float
df['product_minimum_offer_price'] = df['product_minimum_offer_price'].str.replace('$', '') ## Still string
df['product_minimum_offer_price'] = df['product_minimum_offer_price'].str.replace(',', '') ## Clear numbers but still string
df['product_minimum_offer_price'] = df['product_minimum_offer_price'].astype(float) ## Converted to float

In [140]:
df.head()

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.00,169.99,USD,4.0,1319,16,69.88,False,False,True,Only 1 left in stock - order soon.,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",153.99,NaN,USD,4.2,186,4,147.50,False,False,True,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",69.00,99.99,USD,3.8,597,35,64.99,False,False,True,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,49.99,NaN,USD,4.2,2814,3,43.99,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",88.09,98.27,USD,3.8,1338,31,70.40,False,False,True,NaN,False,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN

Handle the Title Column

In [141]:
df['product_title'].unique()

array(['Moto G Play 2023 3-Day Battery Unlocked Made for US 3/32GB 16MP Camera Navy Blue',
       'Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Ring Grip Case Bundle) (Light Blue)',
       'Samsung Galaxy A03s Cell Phone, AT&amp;T GSM Unlocked Android Smartphone, 32GB, Long Lasting Battery, Expandable Storage, 3 Camera Lenses, Infinite Display - Black (Renewed)',
       'TracFone | Motorola Moto g Pure | Locked | 32GB | 4000 mAh Battery | 13 MP Dual Camera System | 6.5&quot; Max Vision HD+ Display | Blue',
       'Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM Unlocked Android Smartphone, 64GB, Long Lasting Battery, Expandable Storage, Triple Lens Camera, Infinite Display, Black (Renewed)',
       'Panasonic Cordless Phone with Answering Machine, Advanced Call Block, Bilingual Caller ID and Easy to Read High-Contrast Display, Expandable System with 2 Handsets - KX-TGD832M (Metallic Black)',
       'Motorola Moto G 5G | 2023 | Unlocked | Made for US 4/128GB | 48 MPCamera | Ink Blue, 163.94x74.98x8.39',
       'Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Light Blue',
       'Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Blue Black',
       'TracFone | Samsung Galaxy A03s | Locked | 32GB | 5000mAh Battery | 48MP Main Camera | 6.5-in. HD+Infinity-V Display | Black',
       'Motorola One Ace | 2021 | 2-Day Battery | Unlocked | Made for US 4/64GB | 48MP Camera | Volcanic Gray',
       'Samsung Galaxy A25 5G A256E 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin Variant/US Compatible LTE) - Blue',
       'SAMSUNG Galaxy A15 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Expandable Storage, Knox Security, Super Fast Charging, US Version, 2024, Blue Black',
       'OnePlus Nord N30 5G | Unlocked Dual-SIM Android Smart Phone | 6.7&quot; LCD Display | 8 +128GB | 5000 mAh Battery | 50W Fast Charging | 108MP Camera | Chromatic Gray',
       'VTech DECT 6.0 Cordless Phone - Blue Display, Big Buttons, Speakerphone, Caller ID, Easy Wall Mount, 1000ft Range - White/Grey',
       'Apple iPhone 13 Mini, 128GB, Blue - Unlocked (Renewed)',
       'Alcatel 1 (16GB) 5.0&quot; Full View Display, Removable Battery, FM Radio, Dual SIM GSM Unlocked US &amp; Global 4G LTE International Version 5033E (Bluish Black)',
       'Samsung Galaxy S21 Ultra 5G, US Version, 128GB, Phantom Black - Unlocked (Renewed)',
       'SAMSUNG Galaxy S24+ Plus Cell Phone, 256GB AI Smartphone, Unlocked Android, 50MP Camera, Fastest Processor, Long Battery Life, US Version, 2024, Onyx Black',
       'Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)',
       'Bold K10 | 2024 | 3-Day Battery | Unlocked | 6.6” HD+ Infinity Display | 128/4GB | Triple 50MP Camera | US Version | US Warranty | Black',
       'AT&amp;T BL102-3 DECT 6.0 3-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Audio Assist, Intercom, and Unsurpassed Range, Silver/Black',
       'SAMSUNG Galaxy S23 FE AI Phone, 128GB Unlocked Android Smartphone, Long Battery Life, Premium Processor, Tough Gorilla Glass Display, Hi-Res 50MP Camera, US Version, 2023, Mint',
       'BLU G63 | 2023 | 3-Day Battery | Unlocked | 6.8” HD+ Infinity Display | 128/4GB | Dual 13MP Camera | US Version | US Warranty | Green',
       'Nokia C2 2E | Android 11 (Go Edition) | Unlocked Smartphone | All Day Battery | 2/32GB | 5.7-Inch Screen | International Version | Blue',
       'Google Pixel 4a with 5G - Android Phone - New Unlocked Smartphone with Night Sight and Ultrawide Lens - Just Black',
       'AT&amp;T TRIMLINE 213 Corded Home Phone with Extra Big Buttons &amp; Visual Ringer. No AC Power Required, Improved Easy-Wall-Mount, Lighted Keypad, 10 Speed Dial Keys, Volume Control, Senior Friendly. White',
       'Samsung Galaxy S20 FE 5G, 128GB, Cloud Navy - Unlocked (Renewed)',
       'Total by Verizon | Samsung Galaxy A03s | Locked | 32GB | 5000mAh Battery | 48MP Main Camera | 6.5-in. HD+Infinity-V Display | Black',
       'TracFone Moto g Pure (2021), 32GB, Blue - Prepaid Smartphone (Locked/Renewed)',
       'Google Pixel 7a - Unlocked Android Cell Phone - Smartphone with Wide Angle Lens and 24-Hour Battery - 128 GB – Charcoal',
       'SAMSUNG Galaxy A15 5G (SM-156M/DSN), 256GB 8GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)',
       'TCL ION Z Unlock Smartphone 4G LTE 32GB - Black',
       'I14 Pro Max Unlocked Smartphone, 6+256GB, Android 13.0 Unlocked Cell Phones, 6.82&quot; HD Screen Battery 6800mAH with 128GB Memory Card/Face ID/Fingerprint Lock/Dual SIM 5G Phone (Blue)',
       'TracFone TCL Flip 2, 8GB, Black - Prepaid Flip Phone (Locked)',
       'Apple iPhone 12 Mini, 64GB, Black - Unlocked (Renewed)',
       'Samsung Galaxy S23 Fan Edition(FE) 5G (SM-S711B/DS) Dual SIM,256GB + 8GB, Factory Unlocked, International Version - No Warranty - (Purple)',
       'Google Pixel 5 - 5G Android Phone - Water Resistant - Unlocked Smartphone with Night Sight and Ultrawide Lens - Just Black',
       'Samsung Galaxy A14 5G A Series, Factory Unlocked, 64GB, US Version, Black (Renewed)',
       'Tracfone Samsung Galaxy A14 5G Locked 64GB 5000mAh Battery 50 MP triple-camera system 6.6-in. FHD+ LCD Display Black',
       'Samsung Galaxy S21 5G, US Version, 128GB, Phantom Gray - Unlocked (Renewed)',
       'Motorola razr | 2023 | Unlocked | Made for US 8/128 | 32MP Camera | Summer Lilac, 73.95 x 170.82 x 7.35mm',
       'Panasonic DECT 6.0 Expandable Cordless Phone System with Answering Machine and Call Blocking - 3 Handsets - KX-TGE633M (Metallic Black)',
       'Apple iPhone SE 2nd Generation, US Version, 64GB, Black - Unlocked (Renewed)',
       'Alcatel SMARTFLIP 4052R | 4G LTE | 4GB Flip-Phone | Bluetooth, WiFi, Big Buttons | Carrier locked to AT&amp;T. Phone is not unlocked - Volcano Black',
       'Apple iPhone 12 Pro, 128GB, Pacific Blue - Fully Unlocked (Renewed)',
       'Motorola Moto Edge 5G UW 256gb Nebula Blue for Verizon (Renewed)',
       'Samsung Galaxy S21 Ultra 5G, US Version, 256GB, Phantom Black - Unlocked (Renewed)',
       'Apple iPhone 12, 128GB, Black - Fully Unlocked (Renewed)',
       'SAMSUNG Galaxy S24 Cell Phone, 256GB AI Smartphone, Unlocked Android, 50MP Camera, Fastest Processor, Long Battery Life, US Version, 2024, Marble Gray',
       'SPIDERCASE Magnetic for iPhone 16 Plus Case,with 2 Pcs [Tempered Glass Screen Protector] Translucent Matte Back Slim Shockproof Protective Phone Case for iPhone 16 Plus 6.7&#x27;&#x27;,Black',
       'Panasonic Cordless Phone with Advanced Call Block, Link2Cell Bluetooth, One-Ring Scam Alert, and 2-Way Recording with Answering Machine, 5 Handsets - KX-TGF975B (Black with Silver Trim)',
       'Apple iPhone 13, 128GB, Red - Unlocked (Renewed)',
       'Samsung Galaxy S21+ 5G, US Version, 128GB, Phantom Black - Unlocked (Renewed)',
       'Samsung Galaxy S20 Ultra, 128GB, Cosmic Black - Fully Unlocked (Renewed)',
       'SAMSUNG Galaxy A35 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Advanced Triple Camera System, Expandable Storage, Rugged Design, US Version, 2024, Awesome Lilac',
       'Motorola Moto G Pure | 2021 | 2-Day battery | Unlocked | Made for US by Motorola | 3/32GB | 13MP Camera | Deep Indigo',
       'Samsung Galaxy S23 Ultra 5G SM-S918B/DS Dual SIM 256GB ROM 8GB RAM GSM Factory Unlocked Global Model (Mobile Cell Phone) (Phantom Green)',
       'Panasonic Compact Cordless Phone with DECT 6.0, 1.6&quot; Amber LCD and Illuminated HS Keypad, Call Block, Caller ID, Multiple Display Languages - 1 Handset - KX-TGB810S (Black/Silver)',
       'Apple iPhone XR, 64GB, Black - Unlocked (Renewed)',
       'Samsung Galaxy S22 Smartphone, Factory Unlocked Android Cell Phone, 128GB, 8K Camera &amp; Video, Brightest Display, Long Battery Life, Fast 4nm Processor, US Version, Phantom Black (Renewed)',
       'OnePlus 12R, 16GB RAM+256GB, Dual-SIM, US Factory Unlocked Android Smartphone, 5500 mAh Battery, 50MP Camera, 80W Fast Charging, 2024, Iron Gray',
       'Moto G Power | 2022 | 3-Day Battery | Unlocked | Made for US by Motorola | 4/64GB | 50 MP Camera | Dark Grove',
       'Samsung Galaxy S20 FE 5G 128GB Blue Verizon (Renewed)',
       'Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Yellow',
       'SAMSUNG,Galaxy A04e (SM-A042M/DS) Dual SIM 32GB,6.5&#x27;&#x27; GSM Unlocked,International Version-Black',
       'Motorola G6 – 32 GB – Unlocked (AT&amp;T/Sprint/T-Mobile/Verizon) – Black - (U.S. Warranty) - PAAE0000US',
       'Samsung Galaxy S21 5G, US Version, 256GB, Phantom Gray - Unlocked (Renewed)',
       'Samsung Galaxy A53 5G A Series Cell Phone, Factory Unlocked Android Smartphone, 128GB, 6.5” FHD Super AMOLED Screen, Long Battery Life, US Version, Black (Renewed)',
       'Samsung Galaxy A12 (32GB, 3GB) 6.5&quot; HD+, Quad Camera, 5000mAh Battery, Global 4G Volte (AT&amp;T Unlocked for T-Mobile, Verizon, Metro) A125U (Black) (Renewed)',
       'SAMSUNG S21 FE 128GB GRAY TMOBILE (Renewed)',
       'Apple iPhone XR, Fully Unlocked, 64 GB - Black (Renewed)',
       'Samsung Galaxy A15 (SM-A155F/DSN), 128GB 4GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Blue Black)',
       'Panasonic Corded/Cordless Phone with Advanced Call Block, 2-Way Recording and Digital Answering Machine, 2 Handsets Expandable up to 6 Cordless Handsets - KX-TGF852B (Black)',
       'VTech SN5147 Amplified Corded/Cordless Senior Phone with Answering Machine, Call Blocking, 90dB Extra-loud Visual Ringer, One-touch Audio Assist on Handset up to 50dB, White',
       'SAMSUNG Galaxy A13 LTE, Factory Unlocked Smartphone, Android Cell Phone, Water Resistant, 50MP Camera, US Version, 32GB, Black (Renewed)',
       'Google Pixel 8a - Unlocked Android Phone with Google AI, Advanced Pixel Camera and 24-Hour Battery - Obsidian - 128 GB',
       'Motorola O212 DECT 6.0 Long Range Cordless Phone - Wireless Phones for Home &amp; Office Phone with Answering Machine - Indoors and Outdoors, Water &amp; Dust Resistant, IP67 Certified - Black, 2 Handsets',
       'SAMSUNG Galaxy A05 (128GB, 4GB) 6.7&quot; Dual SIM Fully Unlocked Global 4G LTE A055M/DS (Black)',
       'Panasonic KX-TG994 DECT 6.0 Bluetooth 4-Handset Phone Bundle',
       'Panasonic Cordless Phone with Answering Machine, Link2Cell Bluetooth, Voice Assistant and Advanced Call Blocking, Expandable System with 4 Handsets - KX-TGD864W (White)',
       'SAMSUNG Galaxy S24 Cell Phone, 256GB AI Smartphone, Unlocked Android, 50MP Camera, Fastest Processor, Long Battery Life, US Version, 2024, Cobalt Violet',
       'Tracfone | Motorola Moto g Play 2024 | Locked | 64GB | 5000mAh Battery | 50MP Quad Pixel Camera | 6.5-in. HD+ 90Hz Display | Sapphire Blue',
       'TracFone Motorola Moto g Play, 32GB, Black - Prepaid Smartphone (Locked)',
       'VTech CS6649 Expandable Corded/Cordless Phone System with Answering System-Caller ID/Call Waiting &amp; Handset/Base Speakerphones',
       'Motorola Moto G14 Dual SIM (2023) 4G LTE (4/128GB) 6.5&quot;&quot; IPS LDC Display | Android 13 | 50MP Rear Camera | 5000mAh Battery | International Model - (Steel Gray), XT2341-2',
       'OnePlus 12,16GB RAM+512GB,Dual-SIM,Unlocked Android Smartphone,Supports 50W Wireless Charging,Latest Mobile Processor,Advanced Hasselblad Camera,5400 mAh Battery,2024,Flowy Emerald',
       'Samsung Galaxy A05s A057M 128GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Light Violet',
       'AT&amp;T 210 Basic Trimline Corded Phone, No AC Power Required, Wall-Mountable, White',
       'AT&amp;T TRIMLINE 210 Corded Home Phone, No AC Power Required, Improved Easy-Wall-Mount, Lighted Big Button Keypad, 13 SpeedDial Keys, Last Number Redial, Mute, Flash, Volume Control, Beige',
       'AT&amp;T GL2101 DECT 6.0 Cordless Home Phone with Call Block, Caller ID, Full-Duplex Handset Speakerphone, 2&quot; White Backlit Display, Lighted Keypad (Graphite &amp; Black)',
       'Nokia G100 | Verizon, T-Mobile, AT&amp;T | Android 12 | Unlocked Smartphone | 3-Day Battery | US Version | 4/128GB | 6.52-Inch Screen | 13MP Triple Camera | Polar Night',
       'DOOGEE S118 4G Rugged Smartphone Unlocked,MTK G99 Android 14 20GB+512GB Waterproof Cell Phone, 6.58&quot; FHD+ 120Hz,10800mAh+ 33W,50MP Rear+32MP Front Rugged Phone, Dual SIM/OTG/GPS/NFC Black',
       'SAMSUNG Galaxy A15 5G 128GB, 6.5&quot;, GSM Unlocked, International Model A156M/DSN (Blue Black)',
       'SAMSUNG Galaxy A25 5G A Series Cell Phone, 128GB Unlocked Android Smartphone, AMOLED Display, Advanced Triple Camera System, Expandable Storage, Stereo Speakers, US Version, 2024, Black',
       'Samsung Galaxy A05 A055M 64GB Dual-SIM GSM Unlocked Android Smartphone (Latin America Version) - Black',
       'OnePlus 7T 8GB RAM 128GB ROM US Model HD1905 Factory Unlocked 6.55 inch AMOLED 90Hz Display Dual SIM Frosted Silver US Warranty',
       'Kyocera DuraForce Pro 2 with Sapphire Shield E6910 Black - Verizon (Renewed)',
       'Samsung Galaxy A10e 32GB A102U GSM Unlocked Phone - Black (Renewed)',
       'Apple iPhone 8 64GB Unlocked - Gray',
       'Samsung Galaxy A01 SM-A015A 16GB 5.7” Single-SIM Android Smartphone (Renewed) (Black, GSM Unlocked)',
       'AT&amp;T CL82267 DECT 6.0 2-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Intercom and Long Range, Black &amp; Wood Grain Finish',
       'Samsung Galaxy A15 5G + 4G LTE (256GB + 8GB) Unlocked (T-Mobile Mint Tello &amp; Global) SM-A156M/DSN Dual Sim Warranty Latin America 6.5&quot; 50MP Triple + (15W Wall Charger) (Blue/Black 1 Year Latin)',
       'Motorola Moto G54 Dual-SIM 256GB ROM + 8GB RAM (Only GSM | No CDMA) Factory Unlocked 5G Smartphone (Midnight Blue) - International Version',
       'Google Pixel 8 - Unlocked Android Smartphone with Advanced Pixel Camera, 24-Hour Battery, and Powerful Security - Hazel - 128 GB',
       'DOOGEE N55 Android 14 Cell Phone,9GB+128GB Expandable 1TB Android Phone,6.56&quot; HD+ 90Hz Unlocked Cell Phone,5150mAh Battery,13MP+8MP,Dual SIM 4G Phone,Face Unlock,OTG/T-Mobile',
       'Samsung Galaxy S22 Ultra 5G Unlocked - 128GB - Black (Renewed)',
       'AT&amp;T CL82219 DECT 6.0 2-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Intercom and Long Range, Black',
       'SAMSUNG Galaxy S23 FE Cell Phone, 256GB, Unlocked Android Smartphone, Long Battery Life, Premium Processor, Tough Gorilla Glass Display, Hi-Res 50MP Camera, US Version, 2023, Cream',
       'SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Blue)',
       'SAMSUNG Galaxy S21+ Plus G996U| Fully Unlocked Android Cell Phone | US Version 5G Smartphone | Pro-Grade Camera, 8K Video, 64MP High Res | 128GB - Phantom Silver - (Renewed)',
       'Cat S22 Flip (16GB) 2.8&quot; Touchscreen, Android 11, IP68 Water Resistant, 4G LTE GSM (T-Mobile Unlocked for MetroPCS, Global) (Black)',
       'AT&amp;T CL82507 DECT 6.0 5-Handset Cordless Phone for Home with Answering Machine, Call Blocking, Caller ID Announcer, Intercom and Long Range, Silver (CL82507)',
       'Reno 11 Pro Unlocked Android Phone 6.7-inch HD LCD Unlocked Cell Phone 8GB+256GB Android 13 Smartphone 6000 mAh Large Battery Unlocked Phone 50MP+13MP Camera Dual SIM (Rock Grey)',
       'ONEPLUS 10T | Moonstone Black | 5G Unlocked Android Smartphone U.S Version | 8GB RAM+128GB Storage (Renewed)',
       'CUBOT KingKong X Rugged Smartphone 5G- 32GB RAM+512GB ROM Cell Phones, 10200mAh Battery, 100MP Camera, 6.58&quot; FHD+1.85&quot; Dual Screen, IP68/IP69K Phone Unlocked, 5G Dual SIM Android 14 Phone, NFC/GPS/OTG',
       'TCL FLIP 4056W 4GB 4G Unlocked GSM Flip Phone - for Senior Easy Use Gray',
       'Nokia 2780 Flip | Unlocked | KaiOS | Verizon, AT&amp;T, T-Mobile | Blue',
       'AT&amp;T EL52513 5-Handset Cordless Phone with Answering System &amp; XL Backlit Keys',
       'DOOGEE Blade 10 Rugged Phone Unlocked Android 14,9GB+128GB/TF 2TB Octa Core Rugged Smartphone,6.56&quot; HD+ 90Hz Cell Phone,16MP Camera,4G Dual SIM IP68/IP69K Waterproof Phone,Widevine L1/GPS/Face ID',
       'VTech IS8151-5 Super Long Range 5 Handset DECT 6.0 Cordless Phone for Home with Answering Machine, 2300 ft Range, Call Blocking, Bluetooth, Headset Jack, Power Backup, Intercom, Expandable to 12 HS',
       'Google Pixel 6a 5G, US Version, 128GB, Charcoal - Unlocked (Renewed)',
       'Apple iPhone 12 Pro Max, 128GB, Pacific Blue - Fully Unlocked (Renewed)',
       'Bold K50 | 5G| 2024 | 3-Day Battery | Unlocked | 6.7” FHD+ 3D AMOLED | 256/8GB | Triple 64MP Camera | US Version | US Warranty | Purple',
       'Cheap Smartphone， 5.0&#x27;&#x27; Android 9.0, 16GB ROM(Extendable to 128GB,Dual SIM Dual Camera, WiFi,Bluetooth,GPS Basic Mobile Phones (R10-Purple)',
       'UMIDIGI G9 5G Cell Phone, Android 14 Unlocked Phones, 12(6+6) GB +128GB/1TB TF Expand, 5G Dual SIM, 50MP Camera, 6.75&quot; HD+ 90Hz Display, AI Face &amp; Fingerprint Unlock, 5000mAh Android Phone Green',
       'SAMSUNG Galaxy XCover6 Pro 5G | Rugged (IP68 Rated) Unlocked (Verizon, AT&amp;T, T-Mobile, US Cellular) | Dual Sim (1 Nano + 1 eSIM) | 128GB | US Version (2022 Model) | Black (SM-G736UZKEXAA)',
       'Samsung Galaxy S23 5G Factory Unlocked 128GB - Phantom Black (Renewed)',
       'BLU Advance L5 | 2020 | Long Lasting Battery | Unlocked | 4.0” Display | 16GB | 5MP Camera | US Warranty | Black',
       'SAMSUNG Galaxy Z Fold 6 AI Cell Phone, 512GB Unlocked Android Smartphone, Circle to Search, Handsfree Live Interpreter, AI Photo Edits, Large Screen, 2024,US 1 Yr Manufacturer Warranty, Silver Shadow',
       'Google Pixel 7 Pro - 5G Android Phone - Unlocked Smartphone with Telephoto, Wide Angle Lens, and 24-Hour Battery - 512GB - Snow',
       'Samsung Galaxy A13 5G (64GB, 4GB) 6.5&quot; HD+, 50MP Triple Camera, 5000mAh Battery, 5G / 4G Volte (for T-Mobile, Metro, Sprint Only) A136U (Black) (Renewed)',
       '[New] VTech VG131-21 DECT 6.0 2-Handset Cordless Phone - Bluetooth Connection, Blue-White Display, Big Buttons, Full Duplex Speakerphone, Caller ID, Easy Wall Mount, 1000ft Range (Black)',
       'Kyocera DuraXV Extreme E4810 Verizon Rugged LTE Flip Basic Cell Phone Camera GPS Black- (Renewed)',
       'Samsung Galaxy S20 Ultra, 128GB, Cosmic Gray - Fully Unlocked (Renewed)',
       'Nokia 110 4G | Dual SIM | GSM Unlocked Mobile Phone | Volte | Blue | International Version | Not AT&amp;T/Cricket/Verizon Compatible',
       'Traditional Red Landline Phone, Retro Corded Telephone with Message Indicator, Classic 2500 Analog Desk Phone, Vintage Corded Desk Telephone Large Button, Old Red Telephone Landline for School,Home',
       'SAMSUNG Galaxy Z Flip 3 5G Factory Unlocked Android Cell Phone US Version Smartphone Flex Mode Intuitive Camera Compact 128GB Storage US Warranty, Phantom Black (Renewed)',
       'MOTOROLA Moto ONE 5G UW ACE 64GB Volcanic Grey-(Verizon)',
       'AT&amp;T DL72319 DECT 6.0 3-Handset Cordless Phone for Home with Connect to Cell, Call Blocking, 1.8&quot; Backlit Screen, Big Buttons, intercom, and Unsurpassed Range',
       'Motorola Edge + |2022| 4800mAh Battery | Unlocked | Made for US 8/512GB | 50MP Camera | Cosmos Blue',
       'Samsung - Galaxy A71 A716U 5G Fully Unlocked 128GB - Prism Cube Black (Renewed)',
       'VTech CS6529-3 3-Handset Expandable Cordless Phone with Answering System-Caller ID/Call Waiting &amp; Backlit Display/Keypad, Silver',
       'OnePlus Nord N200 | 5G for T-Mobile U.S Version | 6.49&quot; Full HD+LCD Screen | 90Hz Smooth Display | Large 5000mAh Battery | Fast Charging | 64GB Storage | Triple Camera (T-Mobile) (Renewed)',

In [142]:
def clean_text(text):
    text = str(text)
    text = re.sub(r'[\|\-\,\(\)]', ' ', text)
    text = re.sub(r'\s+', ' ', text)       
    return text.strip()and text.lower()

df["clean_title"] = df["product_title"].apply(clean_text)

In [143]:
df['clean_title'].unique()

array(['moto g play 2023 3 day battery unlocked made for us 3/32gb 16mp camera navy blue',
       'samsung galaxy a15 sm 155m/dsn 128gb 6gb ram dual sim factory unlocked gsm international version ring grip case bundle light blue ',
       'samsung galaxy a03s cell phone at&amp;t gsm unlocked android smartphone 32gb long lasting battery expandable storage 3 camera lenses infinite display black renewed ',
       'tracfone motorola moto g pure locked 32gb 4000 mah battery 13 mp dual camera system 6.5&quot; max vision hd+ display blue',
       'samsung galaxy a13 5g cell phone at&amp;t gsm unlocked android smartphone 64gb long lasting battery expandable storage triple lens camera infinite display black renewed ',
       'panasonic cordless phone with answering machine advanced call block bilingual caller id and easy to read high contrast display expandable system with 2 handsets kx tgd832m metallic black ',
       'motorola moto g 5g 2023 unlocked made for us 4/128gb 48 mpcamera ink blue 163.94x74.98x8.39',
       'samsung galaxy a15 a155m 128gb dual sim gsm unlocked android smartphone latin america version light blue',
       'samsung galaxy a15 a155m 128gb dual sim gsm unlocked android smartphone latin america version blue black',
       'tracfone samsung galaxy a03s locked 32gb 5000mah battery 48mp main camera 6.5 in. hd+infinity v display black',
       'motorola one ace 2021 2 day battery unlocked made for us 4/64gb 48mp camera volcanic gray',
       'samsung galaxy a25 5g a256e 128gb dual sim gsm unlocked android smartphone latin variant/us compatible lte blue',
       'samsung galaxy a15 5g a series cell phone 128gb unlocked android smartphone amoled display expandable storage knox security super fast charging us version 2024 blue black',
       'oneplus nord n30 5g unlocked dual sim android smart phone 6.7&quot; lcd display 8 +128gb 5000 mah battery 50w fast charging 108mp camera chromatic gray',
       'vtech dect 6.0 cordless phone blue display big buttons speakerphone caller id easy wall mount 1000ft range white/grey',
       'apple iphone 13 mini 128gb blue unlocked renewed ',
       'alcatel 1 16gb 5.0&quot; full view display removable battery fm radio dual sim gsm unlocked us &amp; global 4g lte international version 5033e bluish black ',
       'samsung galaxy s21 ultra 5g us version 128gb phantom black unlocked renewed ',
       'samsung galaxy s24+ plus cell phone 256gb ai smartphone unlocked android 50mp camera fastest processor long battery life us version 2024 onyx black',
       'samsung galaxy a15 sm 155m/dsn 128gb 6gb ram dual sim factory unlocked gsm international version wall charger bundle light blue ',
       'bold k10 2024 3 day battery unlocked 6.6” hd+ infinity display 128/4gb triple 50mp camera us version us warranty black',
       'at&amp;t bl102 3 dect 6.0 3 handset cordless phone for home with answering machine call blocking caller id announcer audio assist intercom and unsurpassed range silver/black',
       'samsung galaxy s23 fe ai phone 128gb unlocked android smartphone long battery life premium processor tough gorilla glass display hi res 50mp camera us version 2023 mint',
       'blu g63 2023 3 day battery unlocked 6.8” hd+ infinity display 128/4gb dual 13mp camera us version us warranty green',
       'nokia c2 2e android 11 go edition unlocked smartphone all day battery 2/32gb 5.7 inch screen international version blue',
       'google pixel 4a with 5g android phone new unlocked smartphone with night sight and ultrawide lens just black',
       'at&amp;t trimline 213 corded home phone with extra big buttons &amp; visual ringer. no ac power required improved easy wall mount lighted keypad 10 speed dial keys volume control senior friendly. white',
       'samsung galaxy s20 fe 5g 128gb cloud navy unlocked renewed ',
       'total by verizon samsung galaxy a03s locked 32gb 5000mah battery 48mp main camera 6.5 in. hd+infinity v display black',
       'tracfone moto g pure 2021 32gb blue prepaid smartphone locked/renewed ',
       'google pixel 7a unlocked android cell phone smartphone with wide angle lens and 24 hour battery 128 gb – charcoal',
       'samsung galaxy a15 5g sm 156m/dsn 256gb 8gb ram dual sim factory unlocked gsm international version wall charger bundle light blue ',
       'tcl ion z unlock smartphone 4g lte 32gb black',
       'i14 pro max unlocked smartphone 6+256gb android 13.0 unlocked cell phones 6.82&quot; hd screen battery 6800mah with 128gb memory card/face id/fingerprint lock/dual sim 5g phone blue ',
       'tracfone tcl flip 2 8gb black prepaid flip phone locked ',
       'apple iphone 12 mini 64gb black unlocked renewed ',
       'samsung galaxy s23 fan edition fe 5g sm s711b/ds dual sim 256gb + 8gb factory unlocked international version no warranty purple ',
       'google pixel 5 5g android phone water resistant unlocked smartphone with night sight and ultrawide lens just black',
       'samsung galaxy a14 5g a series factory unlocked 64gb us version black renewed ',
       'tracfone samsung galaxy a14 5g locked 64gb 5000mah battery 50 mp triple camera system 6.6 in. fhd+ lcd display black',
       'samsung galaxy s21 5g us version 128gb phantom gray unlocked renewed ',
       'motorola razr 2023 unlocked made for us 8/128 32mp camera summer lilac 73.95 x 170.82 x 7.35mm',
       'panasonic dect 6.0 expandable cordless phone system with answering machine and call blocking 3 handsets kx tge633m metallic black ',
       'apple iphone se 2nd generation us version 64gb black unlocked renewed ',
       'alcatel smartflip 4052r 4g lte 4gb flip phone bluetooth wifi big buttons carrier locked to at&amp;t. phone is not unlocked volcano black',
       'apple iphone 12 pro 128gb pacific blue fully unlocked renewed ',
       'motorola moto edge 5g uw 256gb nebula blue for verizon renewed ',
       'samsung galaxy s21 ultra 5g us version 256gb phantom black unlocked renewed ',
       'apple iphone 12 128gb black fully unlocked renewed ',
       'samsung galaxy s24 cell phone 256gb ai smartphone unlocked android 50mp camera fastest processor long battery life us version 2024 marble gray',
       'spidercase magnetic for iphone 16 plus case with 2 pcs [tempered glass screen protector] translucent matte back slim shockproof protective phone case for iphone 16 plus 6.7&#x27;&#x27; black',
       'panasonic cordless phone with advanced call block link2cell bluetooth one ring scam alert and 2 way recording with answering machine 5 handsets kx tgf975b black with silver trim ',
       'apple iphone 13 128gb red unlocked renewed ',
       'samsung galaxy s21+ 5g us version 128gb phantom black unlocked renewed ',
       'samsung galaxy s20 ultra 128gb cosmic black fully unlocked renewed ',
       'samsung galaxy a35 5g a series cell phone 128gb unlocked android smartphone amoled display advanced triple camera system expandable storage rugged design us version 2024 awesome lilac',
       'motorola moto g pure 2021 2 day battery unlocked made for us by motorola 3/32gb 13mp camera deep indigo',
       'samsung galaxy s23 ultra 5g sm s918b/ds dual sim 256gb rom 8gb ram gsm factory unlocked global model mobile cell phone phantom green ',
       'panasonic compact cordless phone with dect 6.0 1.6&quot; amber lcd and illuminated hs keypad call block caller id multiple display languages 1 handset kx tgb810s black/silver ',
       'apple iphone xr 64gb black unlocked renewed ',
       'samsung galaxy s22 smartphone factory unlocked android cell phone 128gb 8k camera &amp; video brightest display long battery life fast 4nm processor us version phantom black renewed ',
       'oneplus 12r 16gb ram+256gb dual sim us factory unlocked android smartphone 5500 mah battery 50mp camera 80w fast charging 2024 iron gray',
       'moto g power 2022 3 day battery unlocked made for us by motorola 4/64gb 50 mp camera dark grove',
       'samsung galaxy s20 fe 5g 128gb blue verizon renewed ',
       'samsung galaxy a15 a155m 128gb dual sim gsm unlocked android smartphone latin america version yellow',
       'samsung galaxy a04e sm a042m/ds dual sim 32gb 6.5&#x27;&#x27; gsm unlocked international version black',
       'motorola g6 – 32 gb – unlocked at&amp;t/sprint/t mobile/verizon – black u.s. warranty paae0000us',
       'samsung galaxy s21 5g us version 256gb phantom gray unlocked renewed ',
       'samsung galaxy a53 5g a series cell phone factory unlocked android smartphone 128gb 6.5” fhd super amoled screen long battery life us version black renewed ',
       'samsung galaxy a12 32gb 3gb 6.5&quot; hd+ quad camera 5000mah battery global 4g volte at&amp;t unlocked for t mobile verizon metro a125u black renewed ',
       'samsung s21 fe 128gb gray tmobile renewed ',
       'apple iphone xr fully unlocked 64 gb black renewed ',
       'samsung galaxy a15 sm a155f/dsn 128gb 4gb ram dual sim factory unlocked gsm international version wall charger bundle blue black ',
       'panasonic corded/cordless phone with advanced call block 2 way recording and digital answering machine 2 handsets expandable up to 6 cordless handsets kx tgf852b black ',
       'vtech sn5147 amplified corded/cordless senior phone with answering machine call blocking 90db extra loud visual ringer one touch audio assist on handset up to 50db white',
       'samsung galaxy a13 lte factory unlocked smartphone android cell phone water resistant 50mp camera us version 32gb black renewed ',
       'google pixel 8a unlocked android phone with google ai advanced pixel camera and 24 hour battery obsidian 128 gb',
       'motorola o212 dect 6.0 long range cordless phone wireless phones for home &amp; office phone with answering machine indoors and outdoors water &amp; dust resistant ip67 certified black 2 handsets',
       'samsung galaxy a05 128gb 4gb 6.7&quot; dual sim fully unlocked global 4g lte a055m/ds black ',
       'panasonic kx tg994 dect 6.0 bluetooth 4 handset phone bundle',
       'panasonic cordless phone with answering machine link2cell bluetooth voice assistant and advanced call blocking expandable system with 4 handsets kx tgd864w white ',
       'samsung galaxy s24 cell phone 256gb ai smartphone unlocked android 50mp camera fastest processor long battery life us version 2024 cobalt violet',
       'tracfone motorola moto g play 2024 locked 64gb 5000mah battery 50mp quad pixel camera 6.5 in. hd+ 90hz display sapphire blue',
       'tracfone motorola moto g play 32gb black prepaid smartphone locked ',
       'vtech cs6649 expandable corded/cordless phone system with answering system caller id/call waiting &amp; handset/base speakerphones',
       'motorola moto g14 dual sim 2023 4g lte 4/128gb 6.5&quot;&quot; ips ldc display android 13 50mp rear camera 5000mah battery international model steel gray xt2341 2',
       'oneplus 12 16gb ram+512gb dual sim unlocked android smartphone supports 50w wireless charging latest mobile processor advanced hasselblad camera 5400 mah battery 2024 flowy emerald',
       'samsung galaxy a05s a057m 128gb dual sim gsm unlocked android smartphone latin america version light violet',
       'at&amp;t 210 basic trimline corded phone no ac power required wall mountable white',
       'at&amp;t trimline 210 corded home phone no ac power required improved easy wall mount lighted big button keypad 13 speeddial keys last number redial mute flash volume control beige',
       'at&amp;t gl2101 dect 6.0 cordless home phone with call block caller id full duplex handset speakerphone 2&quot; white backlit display lighted keypad graphite &amp; black ',
       'nokia g100 verizon t mobile at&amp;t android 12 unlocked smartphone 3 day battery us version 4/128gb 6.52 inch screen 13mp triple camera polar night',
       'doogee s118 4g rugged smartphone unlocked mtk g99 android 14 20gb+512gb waterproof cell phone 6.58&quot; fhd+ 120hz 10800mah+ 33w 50mp rear+32mp front rugged phone dual sim/otg/gps/nfc black',
       'samsung galaxy a15 5g 128gb 6.5&quot; gsm unlocked international model a156m/dsn blue black ',
       'samsung galaxy a25 5g a series cell phone 128gb unlocked android smartphone amoled display advanced triple camera system expandable storage stereo speakers us version 2024 black',
       'samsung galaxy a05 a055m 64gb dual sim gsm unlocked android smartphone latin america version black',
       'oneplus 7t 8gb ram 128gb rom us model hd1905 factory unlocked 6.55 inch amoled 90hz display dual sim frosted silver us warranty',
       'kyocera duraforce pro 2 with sapphire shield e6910 black verizon renewed ',
       'samsung galaxy a10e 32gb a102u gsm unlocked phone black renewed ',
       'apple iphone 8 64gb unlocked gray',
       'samsung galaxy a01 sm a015a 16gb 5.7” single sim android smartphone renewed black gsm unlocked ',
       'at&amp;t cl82267 dect 6.0 2 handset cordless phone for home with answering machine call blocking caller id announcer intercom and long range black &amp; wood grain finish',
       'samsung galaxy a15 5g + 4g lte 256gb + 8gb unlocked t mobile mint tello &amp; global sm a156m/dsn dual sim warranty latin america 6.5&quot; 50mp triple + 15w wall charger blue/black 1 year latin ',
       'motorola moto g54 dual sim 256gb rom + 8gb ram only gsm no cdma factory unlocked 5g smartphone midnight blue international version',
       'google pixel 8 unlocked android smartphone with advanced pixel camera 24 hour battery and powerful security hazel 128 gb',
       'doogee n55 android 14 cell phone 9gb+128gb expandable 1tb android phone 6.56&quot; hd+ 90hz unlocked cell phone 5150mah battery 13mp+8mp dual sim 4g phone face unlock otg/t mobile',
       'samsung galaxy s22 ultra 5g unlocked 128gb black renewed ',
       'at&amp;t cl82219 dect 6.0 2 handset cordless phone for home with answering machine call blocking caller id announcer intercom and long range black',
       'samsung galaxy s23 fe cell phone 256gb unlocked android smartphone long battery life premium processor tough gorilla glass display hi res 50mp camera us version 2023 cream',
       'samsung galaxy a15 5g sm 156m/dsn 128gb 6gb ram dual sim factory unlocked gsm international version wall charger bundle blue ',
       'samsung galaxy s21+ plus g996u fully unlocked android cell phone us version 5g smartphone pro grade camera 8k video 64mp high res 128gb phantom silver renewed ',
       'cat s22 flip 16gb 2.8&quot; touchscreen android 11 ip68 water resistant 4g lte gsm t mobile unlocked for metropcs global black ',
       'at&amp;t cl82507 dect 6.0 5 handset cordless phone for home with answering machine call blocking caller id announcer intercom and long range silver cl82507 ',
       'reno 11 pro unlocked android phone 6.7 inch hd lcd unlocked cell phone 8gb+256gb android 13 smartphone 6000 mah large battery unlocked phone 50mp+13mp camera dual sim rock grey ',
       'oneplus 10t moonstone black 5g unlocked android smartphone u.s version 8gb ram+128gb storage renewed ',
       'cubot kingkong x rugged smartphone 5g 32gb ram+512gb rom cell phones 10200mah battery 100mp camera 6.58&quot; fhd+1.85&quot; dual screen ip68/ip69k phone unlocked 5g dual sim android 14 phone nfc/gps/otg',
       'tcl flip 4056w 4gb 4g unlocked gsm flip phone for senior easy use gray',
       'nokia 2780 flip unlocked kaios verizon at&amp;t t mobile blue',
       'at&amp;t el52513 5 handset cordless phone with answering system &amp; xl backlit keys',
       'doogee blade 10 rugged phone unlocked android 14 9gb+128gb/tf 2tb octa core rugged smartphone 6.56&quot; hd+ 90hz cell phone 16mp camera 4g dual sim ip68/ip69k waterproof phone widevine l1/gps/face id',
       'vtech is8151 5 super long range 5 handset dect 6.0 cordless phone for home with answering machine 2300 ft range call blocking bluetooth headset jack power backup intercom expandable to 12 hs',
       'google pixel 6a 5g us version 128gb charcoal unlocked renewed ',
       'apple iphone 12 pro max 128gb pacific blue fully unlocked renewed ',
       'bold k50 5g 2024 3 day battery unlocked 6.7” fhd+ 3d amoled 256/8gb triple 64mp camera us version us warranty purple',
       'cheap smartphone， 5.0&#x27;&#x27; android 9.0 16gb rom extendable to 128gb dual sim dual camera wifi bluetooth gps basic mobile phones r10 purple ',
       'umidigi g9 5g cell phone android 14 unlocked phones 12 6+6 gb +128gb/1tb tf expand 5g dual sim 50mp camera 6.75&quot; hd+ 90hz display ai face &amp; fingerprint unlock 5000mah android phone green',
       'samsung galaxy xcover6 pro 5g rugged ip68 rated unlocked verizon at&amp;t t mobile us cellular dual sim 1 nano + 1 esim 128gb us version 2022 model black sm g736uzkexaa ',
       'samsung galaxy s23 5g factory unlocked 128gb phantom black renewed ',
       'blu advance l5 2020 long lasting battery unlocked 4.0” display 16gb 5mp camera us warranty black',
       'samsung galaxy z fold 6 ai cell phone 512gb unlocked android smartphone circle to search handsfree live interpreter ai photo edits large screen 2024 us 1 yr manufacturer warranty silver shadow',
       'google pixel 7 pro 5g android phone unlocked smartphone with telephoto wide angle lens and 24 hour battery 512gb snow',
       'samsung galaxy a13 5g 64gb 4gb 6.5&quot; hd+ 50mp triple camera 5000mah battery 5g / 4g volte for t mobile metro sprint only a136u black renewed ',
       '[new] vtech vg131 21 dect 6.0 2 handset cordless phone bluetooth connection blue white display big buttons full duplex speakerphone caller id easy wall mount 1000ft range black ',
       'kyocera duraxv extreme e4810 verizon rugged lte flip basic cell phone camera gps black renewed ',
       'samsung galaxy s20 ultra 128gb cosmic gray fully unlocked renewed ',
       'nokia 110 4g dual sim gsm unlocked mobile phone volte blue international version not at&amp;t/cricket/verizon compatible',
       'traditional red landline phone retro corded telephone with message indicator classic 2500 analog desk phone vintage corded desk telephone large button old red telephone landline for school home',
       'samsung galaxy z flip 3 5g factory unlocked android cell phone us version smartphone flex mode intuitive camera compact 128gb storage us warranty phantom black renewed ',
       'motorola moto one 5g uw ace 64gb volcanic grey verizon ',
       'at&amp;t dl72319 dect 6.0 3 handset cordless phone for home with connect to cell call blocking 1.8&quot; backlit screen big buttons intercom and unsurpassed range',
       'motorola edge + 2022 4800mah battery unlocked made for us 8/512gb 50mp camera cosmos blue',
       'samsung galaxy a71 a716u 5g fully unlocked 128gb prism cube black renewed ',
       'vtech cs6529 3 3 handset expandable cordless phone with answering system caller id/call waiting &amp; backlit display/keypad silver',
       'oneplus nord n200 5g for t mobile u.s version 6.49&quot; full hd+lcd screen 90hz smooth display large 5000mah battery fast charging 64gb storage triple camera t mobile renewed ',
       'apple iphone 11 us version 64gb black t mobile renewed ',
       'at&amp;t cd4930 corded phone with digital answering system and caller id extra large tilt display &amp; buttons black',
       'samsung galaxy s10 128gb 6.1&quot; 4g lte unlocked prism black renewed ',
       'samsung galaxy note 20 5g 128gb 8gb 6.7&quot; amoled+ snapdragon 865 global 5g volte fully unlocked for at&amp;t verizon sprint metro n981u mystic bronze renewed ',
       'vtech cs6719 16 dect 6.0 phone with caller id/call waiting 1 cordless handset red',
       'motorola moto e13 dual sim 64gb rom + 2gb ram factory unlocked 4g smartphone cosmic black international version',
       'at&amp;t el51303 3 handset dect 6.0 cordless home phone full duplex handset speakerphone backlit display lighted keypad caller id/call waiting phonebook eco mode voicemail key quiet mode intercom silver',

## Feature Engineering

Brand Freature

In [144]:
brands = ["Samsung", "Apple", "Motorola", "Nokia", "OnePlus", "VTech", "Panasonic",
           "BLU", "Alcatel", "Moto", "Nokia", "Nord", "Galaxy", "Pixel","iPhone",
             "Redmi", "Realme", "Oppo", "Vivo", "Huawei", "Xiaomi","TCL"]

def extract_brand(text):
    text = text.lower()
    words = text.split()
    first_words = words[:3]

    for brand in brands:
        brand_lower = brand.lower()

        if brand_lower in first_words:
            return brand

    return "Not Famous brand"

df["Brand"] = df["clean_title"].apply(extract_brand)

In [145]:
df['Brand'].unique()

array(['Moto', 'Samsung', 'Motorola', 'Panasonic', 'OnePlus', 'VTech',
       'Apple', 'Alcatel', 'Not Famous brand', 'BLU', 'Nokia', 'Pixel',
       'TCL', 'iPhone', 'Redmi'], dtype=object)

In [146]:
df['Brand']=df['Brand'].replace('Moto', 'Motorola')

In [147]:
df.head(20)

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,...,product_availability,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text,clean_title,Brand
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.00,169.99,USD,4.0,1319,16,69.88,False,...,Only 1 left in stock - order soon.,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN,moto g play 2023 3 day battery unlocked made f...,Motorola
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",153.99,NaN,USD,4.2,186,4,147.50,False,...,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,samsung galaxy a15 sm 155m/dsn 128gb 6gb ram d...,Samsung
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",69.00,99.99,USD,3.8,597,35,64.99,False,...,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN,samsung galaxy a03s cell phone at&amp;t gsm un...,Samsung
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,49.99,NaN,USD,4.2,2814,3,43.99,False,...,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,tracfone motorola moto g pure locked 32gb 4000...,Motorola
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",88.09,98.27,USD,3.8,1338,31,70.40,False,...,NaN,False,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN,samsung galaxy a13 5g cell phone at&amp;t gsm ...,Samsung
5,B0BZG14KFJ,Panasonic Cordless Phone with Answering Machin...,49.99,59.99,USD,4.4,3843,3,25.19,False,...,NaN,False,4K+ bought in past month,"FREE delivery Tue, Sep 24",False,$25.00,2.0,NaN,panasonic cordless phone with answering machin...,Panasonic
6,B0C2SWQBMB,Motorola Moto G 5G | 2023 | Unlocked | Made fo...,149.99,249.99,USD,4.2,2637,8,100.72,False,...,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN,motorola moto g 5g 2023 unlocked made for us 4...,Motorola
7,B0CTD47P22,Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...,149.50,158.00,USD,4.2,253,9,146.50,False,...,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung
8,B0CSB14R7J,Samsung Galaxy A15 A155M 128GB Dual-SIM GSM Un...,139.99,NaN,USD,4.3,573,15,136.62,False,...,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung
9,B0CHK6LWKZ,TracFone | Samsung Galaxy A03s | Locked | 32GB...,59.99,NaN,USD,4.0,258,4,50.48,False,...,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,tracfone samsung galaxy a03s locked 32gb 5000m...,Samsung
10,B0C5BMB1WB,Motorola One Ace | 2021 | 2-Day Battery | Unlo...,89.00,NaN,USD,4.0,204,10,85.44,False,...,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,motorola one ace 2021 2 day battery unlocked m...,Motorola
11,B0CRVWPWKP,Samsung Galaxy A25 5G A256E 128GB Dual-SIM GSM...,195.00,NaN,USD,4.0,259,15,164.50,False,...,NaN,False,400+ bought in past month,"FREE delivery Wed, Sep 25",True,NaN,NaN,NaN,samsung galaxy a25 5g a256e 128gb dual sim gsm...,Samsung
12,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,NaN,USD,4.0,610,2,154.00,False,...,NaN,True,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN,samsung galaxy a15 5g a series cell phone 128g...,Samsung
13,B0C22BRGLG,OnePlus Nord N30 5G | Unlocked Dual-SIM Androi...,249.99,299.99,USD,4.3,963,5,209.28,False,...,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,oneplus nord n30 5g unlocked dual sim android ...,OnePlus
14,B09NZQJRN7,"VTech DECT 6.0 Cordless Phone - Blue Display, ...",18.45,NaN,USD,4.3,9096,2,13.84,False,...,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,vtech dect 6.0 cordless phone blue display big...,VTech
15,B09LKXHWCF,"Apple iPhone 13 Mini, 128GB, Blue - Unlocked (...",355.81,415.00,USD,4.1,4265,20,303.99,False,...,NaN,True,500+ bought in past month,"FREE delivery Tomorrow, Sep 20",True,NaN,NaN,NaN,apple iphone 13 mini 128gb blue unlocked renewed,Apple
16,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",153.99,NaN,USD,4.2,186,4,147.50,False,...,NaN,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,samsung galaxy a15 sm 155m/dsn 128gb 6gb ram d...,Samsung
17,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.00,169.99,USD,4.0,1319,16,69.88,False,...,Only 3 left in stock - order soon.,False,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 3 left in stock...",False,NaN,NaN,NaN,moto g play 2023 3 day battery unlocked made f...,Motorola
18,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",69.00,99.99,USD,3.8,597,35,64.99,False,...,NaN,False,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN,samsung galaxy a03s cell phone at&amp;t gsm un...,Samsung
19,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,49.99,NaN,USD,4.2,2814,3,43.99,False,...,NaN,False,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,tracfone motorola moto g pure locked 32gb 4000...,Motorola

Product Type

In [148]:
def extract_type(text):
    text = text.lower()

    if "charger" in text or "power bank" in text:
        return "Charger"
    
    if "cordless phone" in text or "landline phone"in text or "landline phone" in text or "cordless "in text:
        return "Home Phone"
    
    if "holder" in text or "mount" in text:
        return "Holder"
    
    if "tripod" in text:
        return "Tripod"
    
    if "compatible with iphone" in text or "for iphone" in text or "Compatible with Apple iPhone, iPad, and iPod" in text:
        pass 
    elif "iphone" in text:
        return "iPhone"
    
    if "with case" in text or "case bundle" in text or "charger bundle" in text  :
        return "Smartphone with bundle"
    
    if( "case" in text or "cover" in text or 
       "casing" in text or "shell" in text or
        "bumper" in text or "sleeve" in text or "pouch" in text or 
     "holster" in text or"spidercase" in text) : 
        return "Case" 

    
    if ("headphones" in text or "earbuds" in text or 
        "earphones" in text or "headset" in text 
        or "corded speakerphone" in text) :
        return "Headphones"
    
    if "flip phone"in text or "flip"in text:
        return "Flip Phone"
    
    if ("smartphone" in text or "cell phone" in text or "android" in text 
        or "galaxy" in text or "moto" in text or "nord" in text or "nokia" in text 
        or "oneplus" in text or "pixel" in text or "redmi" in text or "realme" in text
        or "oppo" in text or "vivo" in text or "huawei" in text or "xiaomi" in text
        or "samsung" in text or "Flip Phone" in text 
        or " dual sim" in text ):
        return "Smartphone"
    
    
    
    else:
        return "Other"

df["Product_Type"] = df["clean_title"].apply(extract_type)

In [149]:
df['Product_Type'].unique()

array(['Smartphone', 'Smartphone with bundle', 'Home Phone', 'iPhone',
       'Charger', 'Other', 'Holder', 'Flip Phone', 'Case', 'Headphones',
       'Tripod'], dtype=object)

In [150]:
df[df['Product_Type']=="Other"]

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,...,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text,clean_title,Brand,Product_Type
34,B0D5T7318W,Bold K10 | 2024 | 3-Day Battery | Unlocked | 6...,99.99,NaN,USD,3.6,17,6,98.97,False,...,False,200+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,bold k10 2024 3 day battery unlocked 6.6” hd+ ...,Not Famous brand,Other
37,B0CSF1MRRR,BLU G63 | 2023 | 3-Day Battery | Unlocked | 6....,89.99,129.99,USD,3.9,92,5,79.99,False,...,False,300+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,blu g63 2023 3 day battery unlocked 6.8” hd+ i...,BLU,Other
95,B09D2ZJLLV,Panasonic KX-TG994 DECT 6.0 Bluetooth 4-Handse...,89.97,NaN,USD,4.4,382,14,79.00,False,...,False,700+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,panasonic kx tg994 dect 6.0 bluetooth 4 handse...,Panasonic,Other
113,B07VCB7P1L,Kyocera DuraForce Pro 2 with Sapphire Shield E...,72.25,91.00,USD,3.5,381,7,64.30,False,...,True,50+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,kyocera duraforce pro 2 with sapphire shield e...,Not Famous brand,Other
144,B0D897WH4K,Bold K50 | 5G| 2024 | 3-Day Battery | Unlocked...,199.99,NaN,USD,4.1,21,1,199.99,False,...,False,300+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,bold k50 5g 2024 3 day battery unlocked 6.7” f...,Not Famous brand,Other
149,B07Z6Q9NCZ,BLU Advance L5 | 2020 | Long Lasting Battery |...,NaN,NaN,NaN,3.3,3035,1,NaN,False,...,False,50+ bought in past month,NaN,False,NaN,NaN,NaN,blu advance l5 2020 long lasting battery unloc...,BLU,Other
166,B0764KJ4RK,AT&amp;T CD4930 Corded Phone with Digital Answ...,49.85,NaN,USD,4.4,13525,3,17.57,False,...,False,400+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,at&amp;t cd4930 corded phone with digital answ...,Not Famous brand,Other
182,B09Q7JLN13,SIMBROS Radiant Core Phone At&amp;t Unlocked u...,39.99,49.99,USD,3.0,58,1,39.99,False,...,True,50+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,simbros radiant core phone at&amp;t unlocked u...,Not Famous brand,Other
183,B0CL7RDZXD,BLU C5 Max | Unlocked | 5.7” HD+ Display | 5MP...,54.99,NaN,USD,3.3,679,2,44.99,False,...,False,100+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN,blu c5 max unlocked 5.7” hd+ display 5mp camer...,BLU,Other
216,B0757B9VFG,VTech AM18447 Main Console 4-Line Expandable S...,149.95,164.95,USD,4.3,1161,6,55.94,False,...,False,300+ bought in past month,"FREE delivery Thu, Sep 26 Or fastest delivery ...",False,NaN,NaN,NaN,vtech am18447 main console 4 line expandable s...,VTech,Other
220,B003BNY7QG,AT&amp;T ML17939 2-Line Corded Telephone with ...,70.32,87.95,USD,4.3,1082,83,40.32,False,...,False,200+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,at&amp;t ml17939 2 line corded telephone with ...,Not Famous brand,Other
224,B0CJB9FW71,BLU G73 | 2023 | 3-Day Battery | Unlocked | 6....,114.99,NaN,USD,3.9,165,4,40.00,False,...,False,More Buying Choices,"FREE delivery Thu, Sep 26",True,NaN,NaN,NaN,blu g73 2023 3 day battery unlocked 6.8” hd+ i...,BLU,Other
240,B0CZRJMN8G,"Big Button Phone for Seniors, Corded Landline ...",29.99,NaN,USD,4.5,25,1,29.99,False,...,False,300+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,Save 5% with coupon,big button phone for seniors corded landline t...,Not Famous brand,Other
246,B004KQDBKG,Panasonic KX-TS880B Integrated Corded Telephon...,55.00,59.99,USD,3.9,862,3,16.41,False,...,False,50+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,panasonic kx ts880b integrated corded telephon...,Panasonic,Other
249,B08M46Q3C1,"Panasonic Office Phone System, Corded Base Sta...",146.29,169.99,USD,3.8,136,23,61.19,False,...,False,100+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,panasonic office phone system corded base stat...,Panasonic,Other
253,B0B7KNC1CM,"SMPL Big Button Phone for Seniors, Simple Cord...",64.99,NaN,USD,4.1,1952,1,64.99,False,...,False,50+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,smpl big button phone for seniors simple corde...,Not Famous brand,Other
254,B001TK3DLS,AT&amp;T TR1909B Trimline Corded Phone with Ca...,23.04,NaN,USD,4.1,2406,45,13.73,False,...,False,100+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,at&amp;t tr1909b trimline corded phone with ca...,Not Famous brand,Other
257,B07DVTRK72,"Y043 Corded Landline Telephone for Home, Calle...",18.98,29.98,USD,3.8,1235,1,18.98,False,...,False,100+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,y043 corded landline telephone for home caller...,Not Famous brand,Other
258,B0D749T6DG,Gabb Phone 4 Pro The Safe Phone Built for Teen...,199.99,NaN,USD,4.5,29,1,199.99,False,...,True,50+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,gabb phone 4 pro the safe phone built for teen...,Not Famous brand,Other
262,B0016ALH32,XL88Q - Easy to Use One-Piece Telephone with R...,19.99,NaN,USD,4.2,211,3,17.20,False,...,True,200+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,xl88q easy to use one piece telephone with rin...,Not Famous brand,Other
270,B0016CVUR8,Hamburger Cheeseburger Burger Phone Telephone ...,12.98,15.80,USD,4.3,1079,8,12.00,False,...,False,100+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,hamburger cheeseburger burger phone telephone ...,Not Famous brand,Other
272,B09GKPDCVW,Yealink W76P - IP DECT Phone Bundle W56H with ...,161.23,179.99,USD,4.2,155,31,95.00,False,...,False,200+ bought in past month,"FREE delivery Tue, Sep 24 Only 11 left in stoc...",False,NaN,NaN,NaN,yealink w76p ip dect phone bundle w56h with w7...,Not Famous brand,Other
295,B00ZYHA1KI,Hamilton CapTel 2400i Captioned Telephone Larg...,75.00,NaN,USD,4.3,1603,4,59.99,False,...,False,300+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,hamilton captel 2400i captioned telephone larg...,Not Famous brand,Other
317,B003DNSA6M,XBLUE Add-on Phone for X16 Office Phone System...,199.99,NaN,USD,4.3,115,2,69.94,False,...,False,More Buying Choices,"FREE delivery Thu, Sep 26 Or fastest delivery ...",False,NaN,NaN,NaN,xblue add on phone for x16 office phone system...,Not Famous brand,Other
327,B09P3LLRGG,It can Edit 9 one Touch Memory Speed Dialing a...,29.99,NaN,USD,3.9,284,2,21.99,False,...,False,200+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,it can edit 9 one touch memory speed dialing a...,Not Famous brand,Other
332,B0D3WTGSJY,"Ring Light [3 Color, 5 Brightness &amp; Timer]...",15.99,NaN,USD,4.4,82,1,15.99,False,...,False,500+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,ring light [3 color 5 brightness &amp; timer] ...,Not Famous brand,Other

In [151]:
df[df['asin']=="B085TCRFST"]

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,...,climate_pledge_friendly,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text,clean_title,Brand,Product_Type
30,B085TCRFST,"Alcatel 1 (16GB) 5.0&quot; Full View Display, ...",41.99,44.7,USD,3.6,2048,7,29.7,False,...,False,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,alcatel 1 16gb 5.0&quot; full view display rem...,Alcatel,Smartphone

In [152]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_title                340 non-null    object
 2   product_price                336 non-null    float64
 3   product_original_price       148 non-null    float64
 4   currency                     336 non-null    object
 5   product_star_rating          337 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  336 non-null    float64
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         75 non-null     object
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 320 non-null    object
 15  delivery                     337 non-null    object
 16  has_variations               340 non-null    bool
 17  unit_price                   4 non-null      object
 18  unit_count                   4 non-null      float64
 19  coupon_text                  22 non-null     object
 20  clean_title                  340 non-null    object
 21  Brand                        340 non-null    object
 22  Product_Type                 340 non-null    object
dtypes: bool(5), float64(5), int64(2), object(11)
memory usage: 49.6+ KB

Prices Columns

In [153]:
# fill nans in price column with the mean price
median_price = df['product_price'].median()
df['product_price']=df['product_price'].fillna(median_price)

In [154]:
#fill nulls in original price with the price column
df["product_original_price"] = df["product_original_price"].fillna(df["product_price"])

In [155]:
#Discount percentage 
df["discount_percent"] = ((df["product_original_price"] - df["product_price"]) / df["product_original_price"]) * 100

In [156]:
df

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,...,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text,clean_title,Brand,Product_Type,discount_percent
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.00,169.99,USD,4.0,1319,16,69.88,False,...,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN,moto g play 2023 3 day battery unlocked made f...,Motorola,Smartphone,41.761280
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",153.99,153.99,USD,4.2,186,4,147.50,False,...,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,samsung galaxy a15 sm 155m/dsn 128gb 6gb ram d...,Samsung,Smartphone with bundle,0.000000
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",69.00,99.99,USD,3.8,597,35,64.99,False,...,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN,samsung galaxy a03s cell phone at&amp;t gsm un...,Samsung,Smartphone,30.993099
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,49.99,49.99,USD,4.2,2814,3,43.99,False,...,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,tracfone motorola moto g pure locked 32gb 4000...,Motorola,Smartphone,0.000000
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",88.09,98.27,USD,3.8,1338,31,70.40,False,...,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN,samsung galaxy a13 5g cell phone at&amp;t gsm ...,Samsung,Smartphone,10.359214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,B0CZ3YPSRX,"Gimbal Stabilizer for Smartphone, 3-Axis Phone...",99.99,99.99,USD,4.7,8,1,99.99,False,...,NaN,"FREE delivery Thu, Sep 26",False,NaN,NaN,Save 50% with coupon,gimbal stabilizer for smartphone 3 axis phone ...,Not Famous brand,Smartphone,0.000000
336,B0CHB24KQJ,[True Military-Grade] Car Phone Holder【2024 St...,39.99,45.99,USD,4.4,2589,1,39.99,False,...,50+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,[true military grade] car phone holder【2024 st...,Not Famous brand,Holder,13.046314
337,B01LXOPZ4W,Wall Mount Cell Phone Charging Shelf | Multi-D...,273.00,273.00,USD,4.1,45,1,273.00,False,...,NaN,FREE delivery Sep 25 - 30,False,NaN,NaN,NaN,wall mount cell phone charging shelf multi dev...,Not Famous brand,Holder,0.000000
338,B0CXPJK7F7,"Sensyne 92&quot; Cell Phone Tripod, Selfie Sti...",29.99,29.99,USD,4.6,29066,1,29.99,True,...,300+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,sensyne 92&quot; cell phone tripod selfie stic...,Not Famous brand,Tripod,0.000000
339,B0CQ237PFS,Portable Charger 33800mAh USB C Power Bank wit...,45.95,69.95,USD,4.4,672,1,45.95,False,...,3K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,Save 20% with coupon,portable charger 33800mah usb c power bank wit...,Not Famous brand,Charger,34.310222

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_title                340 non-null    object
 2   product_price                340 non-null    float64
 3   product_original_price       340 non-null    float64
 4   currency                     336 non-null    object
 5   product_star_rating          337 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  336 non-null    float64
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         75 non-null     object
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 320 non-null    object
 15  delivery                     337 non-null    object
 16  has_variations               340 non-null    bool
 17  unit_price                   4 non-null      object
 18  unit_count                   4 non-null      float64
 19  coupon_text                  22 non-null     object
 20  clean_title                  340 non-null    object
 21  Brand                        340 non-null    object
 22  Product_Type                 340 non-null    object
 23  discount_percent             340 non-null    float64
dtypes: bool(5), float64(6), int64(2), object(11)
memory usage: 52.3+ KB

Stars Column

In [158]:
df["product_star_rating"].unique()

array([4. , 4.2, 3.8, 4.4, 4.3, 4.1, 3.6, 3.9, 4.5, 3.3, nan, 4.7, 3.7,
       3.4, 3.5, 2.8, 3. , 5. , 3.2, 4.8, 1.6, 4.6, 2.7])

In [159]:
df["product_star_rating"] = df["product_star_rating"].fillna(0)

In [160]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_title                340 non-null    object
 2   product_price                340 non-null    float64
 3   product_original_price       340 non-null    float64
 4   currency                     336 non-null    object
 5   product_star_rating          340 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  336 non-null    float64
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         75 non-null     object
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 320 non-null    object
 15  delivery                     337 non-null    object
 16  has_variations               340 non-null    bool
 17  unit_price                   4 non-null      object
 18  unit_count                   4 non-null      float64
 19  coupon_text                  22 non-null     object
 20  clean_title                  340 non-null    object
 21  Brand                        340 non-null    object
 22  Product_Type                 340 non-null    object
 23  discount_percent             340 non-null    float64
dtypes: bool(5), float64(6), int64(2), object(11)
memory usage: 52.3+ KB

In [161]:
df['product_minimum_offer_price'] .unique()

array([  69.88,  147.5 ,   64.99,   43.99,   70.4 ,   25.19,  100.72,
        146.5 ,  136.62,   50.48,   85.44,  164.5 ,  154.  ,  209.28,
         13.84,  303.99,   29.7 ,  244.99,  741.99,  123.7 ,   98.97,
         38.25,  451.19,   79.99,   57.44,  153.28,   13.28,  134.85,
         49.21,   24.99,  318.  ,  176.35,   39.  ,  158.99,   19.99,
        203.31,  429.5 ,  149.95,   88.98,  164.99,  331.64,   49.52,
         96.69,   22.95,  353.72,   89.22,  283.95,  284.92,     nan,
          9.99,   98.03,  305.96,  179.  ,  224.93,  313.91,   80.04,
        759.5 ,   12.14,  155.99,  204.  ,  493.11,   79.79,  133.99,
        119.5 ,   70.  ,   59.95,  127.16,   74.74,  162.82,  169.99,
         99.5 ,   74.99,   29.95,   81.4 ,  383.04,  129.95,   94.76,
         79.  ,   46.2 ,  724.02,   49.99,   36.84,  102.96,  715.67,
        117.9 ,    8.61,    9.65,   14.85,   56.08,  299.99,  127.7 ,
        164.31,   95.97,   64.3 ,   68.95,   89.99,   67.89,   32.72,
        174.99,  139.5 ,  475.  ,  139.99,  339.  ,   27.67,  451.85,
        187.  ,   49.9 ,   57.19,   99.99,  204.95,  399.99,   62.99,
         41.21,   62.42,  199.99,   51.94,  139.85,  449.99,   51.99,
        143.99,   98.99,  325.05, 1583.65,  485.  ,   77.67,  125.98,
        223.95,   31.59,   33.27,  204.99,   50.  ,   34.68,  192.55,
        111.1 ,   35.25,  209.  ,   17.57,  190.95,   10.99,   67.7 ,
         29.65,  359.5 ,  169.  ,   36.35,   37.25,  615.99,   14.99,
        149.99,   48.03,  319.95,  188.89,   39.99,   44.99,  143.54,
        319.99,   92.89,   32.95,   56.1 ,   74.63,  156.  ,  335.72,
        294.  ,  859.99,   21.99,  119.99, 1138.07,  473.5 ,  135.62,
         68.49,   59.39,   82.17,   69.99,  199.5 ,   34.63,   14.19,
         48.26,    7.99,   67.69,   55.94,  279.99,   75.26,   64.89,
         40.32,   28.73,   17.24,  109.85,   40.  ,   38.11,   64.57,
         44.34,   72.76,  125.  ,  213.91,  289.  ,  217.95,   80.  ,
        899.99,  128.95,   95.09,  109.9 ,  177.95,   29.99,   61.03,
         28.95,   14.8 ,   89.95,   17.63,   16.41,   13.98,   34.48,
         61.19,  159.69,   59.99,   13.73,   25.93,   56.58,   18.98,
        184.95,   68.99,   17.2 ,   34.74,  109.95,   36.71,  150.  ,
         73.99,   17.99,   12.  ,    8.89,   95.  ,   65.99,  214.99,
        134.  ,   84.55,  195.24,   45.77,   26.93,  511.67,   14.97,
         62.22,   69.94,  164.35,   13.89,  103.9 ,   43.89,  117.7 ,
         67.17,   62.01,   22.99,  283.69,  109.99,  134.99,  164.95,
         49.27,   27.98,  335.99,   65.35,   41.84,  640.28,  244.97,
       1151.04,  993.9 ,   49.  ,  119.9 ,   34.98,  219.  ,  125.99,
        101.15,   34.99,  139.  ,   15.99,  135.99,   27.49,  273.  ,
         45.95])

In [162]:
## Fill the nan values in the minimum offer price column with the price column
df["product_minimum_offer_price"] = df["product_minimum_offer_price"].fillna(df["product_price"])

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_title                340 non-null    object
 2   product_price                340 non-null    float64
 3   product_original_price       340 non-null    float64
 4   currency                     336 non-null    object
 5   product_star_rating          340 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  340 non-null    float64
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         75 non-null     object
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 320 non-null    object
 15  delivery                     337 non-null    object
 16  has_variations               340 non-null    bool
 17  unit_price                   4 non-null      object
 18  unit_count                   4 non-null      float64
 19  coupon_text                  22 non-null     object
 20  clean_title                  340 non-null    object
 21  Brand                        340 non-null    object
 22  Product_Type                 340 non-null    object
 23  discount_percent             340 non-null    float64
dtypes: bool(5), float64(6), int64(2), object(11)
memory usage: 52.3+ KB

In [164]:
df['product_availability'].unique()

array(['Only 1 left in stock - order soon.', nan,
       'Only 3 left in stock - order soon.',
       'Only 6 left in stock - order soon.',
       'Only 9 left in stock - order soon.',
       'Only 20 left in stock - order soon.',
       'Only 12 left in stock - order soon.',
       'Only 8 left in stock - order soon.',
       'Only 4 left in stock - order soon.',
       'Only 11 left in stock - order soon.',
       'Only 17 left in stock - order soon.',
       'Only 2 left in stock - order soon.',
       'Only 15 left in stock - order soon.',
       'Only 10 left in stock - order soon.',
       'Only 5 left in stock - order soon.',
       'Only 13 left in stock - order soon.',
       'Only 7 left in stock - order soon.',
       'Only 14 left in stock - order soon.',
       'Only 13 left in stock (more on the way).',
       'Only 16 left in stock - order soon.',
       'Only 19 left in stock - order soon.',
       'Only 18 left in stock - order soon.'], dtype=object)

In [165]:
df[df['product_availability'].isna()]

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,...,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text,clean_title,Brand,Product_Type,discount_percent
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",153.99,153.99,USD,4.2,186,4,147.50,False,...,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,samsung galaxy a15 sm 155m/dsn 128gb 6gb ram d...,Samsung,Smartphone with bundle,0.000000
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",69.00,99.99,USD,3.8,597,35,64.99,False,...,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN,samsung galaxy a03s cell phone at&amp;t gsm un...,Samsung,Smartphone,30.993099
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,49.99,49.99,USD,4.2,2814,3,43.99,False,...,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,tracfone motorola moto g pure locked 32gb 4000...,Motorola,Smartphone,0.000000
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",88.09,98.27,USD,3.8,1338,31,70.40,False,...,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN,samsung galaxy a13 5g cell phone at&amp;t gsm ...,Samsung,Smartphone,10.359214
5,B0BZG14KFJ,Panasonic Cordless Phone with Answering Machin...,49.99,59.99,USD,4.4,3843,3,25.19,False,...,4K+ bought in past month,"FREE delivery Tue, Sep 24",False,$25.00,2.0,NaN,panasonic cordless phone with answering machin...,Panasonic,Home Phone,16.669445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,B0CZ3YPSRX,"Gimbal Stabilizer for Smartphone, 3-Axis Phone...",99.99,99.99,USD,4.7,8,1,99.99,False,...,NaN,"FREE delivery Thu, Sep 26",False,NaN,NaN,Save 50% with coupon,gimbal stabilizer for smartphone 3 axis phone ...,Not Famous brand,Smartphone,0.000000
336,B0CHB24KQJ,[True Military-Grade] Car Phone Holder【2024 St...,39.99,45.99,USD,4.4,2589,1,39.99,False,...,50+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,[true military grade] car phone holder【2024 st...,Not Famous brand,Holder,13.046314
337,B01LXOPZ4W,Wall Mount Cell Phone Charging Shelf | Multi-D...,273.00,273.00,USD,4.1,45,1,273.00,False,...,NaN,FREE delivery Sep 25 - 30,False,NaN,NaN,NaN,wall mount cell phone charging shelf multi dev...,Not Famous brand,Holder,0.000000
338,B0CXPJK7F7,"Sensyne 92&quot; Cell Phone Tripod, Selfie Sti...",29.99,29.99,USD,4.6,29066,1,29.99,True,...,300+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,sensyne 92&quot; cell phone tripod selfie stic...,Not Famous brand,Tripod,0.000000
339,B0CQ237PFS,Portable Charger 33800mAh USB C Power Bank wit...,45.95,69.95,USD,4.4,672,1,45.95,False,...,3K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,Save 20% with coupon,portable charger 33800mah usb c power bank wit...,Not Famous brand,Charger,34.310222

In [166]:
# fill nans in  product_availability column with "in stock"
df['product_availability'] = df['product_availability'].fillna("In Stock")

In [167]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_title                340 non-null    object
 2   product_price                340 non-null    float64
 3   product_original_price       340 non-null    float64
 4   currency                     336 non-null    object
 5   product_star_rating          340 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  340 non-null    float64
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         340 non-null    object
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 320 non-null    object
 15  delivery                     337 non-null    object
 16  has_variations               340 non-null    bool
 17  unit_price                   4 non-null      object
 18  unit_count                   4 non-null      float64
 19  coupon_text                  22 non-null     object
 20  clean_title                  340 non-null    object
 21  Brand                        340 non-null    object
 22  Product_Type                 340 non-null    object
 23  discount_percent             340 non-null    float64
dtypes: bool(5), float64(6), int64(2), object(11)
memory usage: 52.3+ KB

In [168]:
df['sales_volume'].unique()

array(['4K+ bought in past month', '1K+ bought in past month',
       '2K+ bought in past month', '500+ bought in past month',
       '400+ bought in past month', '200+ bought in past month',
       '3K+ bought in past month', '300+ bought in past month',
       '900+ bought in past month', '50+ bought in past month',
       '100+ bought in past month', 'List: ', '600+ bought in past month',
       '700+ bought in past month', nan, 'More Buying Choices',
       'Typical: ', 'Typical price: ',
       'Shop products from small business brands sold in Amazon’s store. Discover more about the small businesses partnering with Amazon and Amazon’s commitment to empowering them.'],
      dtype=object)

In [169]:
# fill nans in  sales_volume column with " Normal or Less then normal sales "
df['sales_volume'] = df['sales_volume'].fillna(" Normal or Less then normal sales ")

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 24 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_title                340 non-null    object
 2   product_price                340 non-null    float64
 3   product_original_price       340 non-null    float64
 4   currency                     336 non-null    object
 5   product_star_rating          340 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  340 non-null    float64
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         340 non-null    object
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 340 non-null    object
 15  delivery                     337 non-null    object
 16  has_variations               340 non-null    bool
 17  unit_price                   4 non-null      object
 18  unit_count                   4 non-null      float64
 19  coupon_text                  22 non-null     object
 20  clean_title                  340 non-null    object
 21  Brand                        340 non-null    object
 22  Product_Type                 340 non-null    object
 23  discount_percent             340 non-null    float64
dtypes: bool(5), float64(6), int64(2), object(11)
memory usage: 52.3+ KB

In [171]:
df['delivery'].unique()

array(['FREE delivery Tue, Sep 24 Only 1 left in stock - order soon.',
       'FREE delivery Tue, Sep 24', 'FREE delivery Mon, Sep 30',
       'FREE delivery Wed, Sep 25',
       'FREE delivery Tue, Sep 24 on $35 of items shipped by Amazon',
       'FREE delivery Tomorrow, Sep 20',
       'FREE delivery Tue, Sep 24 Only 3 left in stock - order soon.',
       '$10.33 delivery Fri, Oct 4',
       'FREE delivery Wed, Sep 25 Only 6 left in stock - order soon.',
       'FREE delivery', 'FREE delivery Fri, Sep 27',
       'FREE delivery on $35 shipped by Amazon.Temporarily out of stock.',
       'FREE delivery Sep 24 - 26 Or fastest delivery Sep 23 - 25',
       'FREE delivery Sep 24 - 26 Or fastest delivery Tomorrow, Sep 20 Only 1 left in stock - order soon.',
       'FREE delivery Wed, Sep 25 Only 9 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Or fastest delivery Tomorrow, Sep 20 Only 20 left in stock - order soon.',
       'FREE delivery Sep 23 - 24 Only 1 left in stock - order soon.',
       'FREE delivery Tomorrow, Sep 20 Only 12 left in stock - order soon.',
       'FREE delivery Sep 25 - 27 Or fastest delivery Tomorrow, Sep 20',
       'FREE delivery Tue, Sep 24 Only 8 left in stock - order soon.',
       'FREE delivery Sep 24 - 26 Only 1 left in stock - order soon.',
       'FREE delivery Thu, Sep 26',
       'FREE delivery Sat, Sep 21 Only 4 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Or fastest delivery Tomorrow, Sep 20',
       'FREE delivery Fri, Sep 27 Or fastest delivery Tomorrow, Sep 20 Only 11 left in stock - order soon.',
       'FREE delivery Tue, Sep 24 Only 17 left in stock - order soon.',
       'FREE delivery Sep 23 - 24 Only 20 left in stock - order soon.',
       'FREE delivery Sep 23 - 25 Only 2 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Or fastest delivery Tomorrow, Sep 20 Only 3 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Or fastest delivery Tomorrow, Sep 20 Only 15 left in stock - order soon.',
       'FREE deliveryOnly 10 left in stock - order soon.',
       'FREE delivery Sep 20 - 23 Only 1 left in stock - order soon.',
       'FREE delivery Wed, Oct 2 Only 6 left in stock - order soon.',
       'FREE delivery Thu, Sep 26 on $35 of items shipped by AmazonOr fastest delivery Tue, Sep 24',
       nan, 'FREE delivery Sat, Sep 21',
       'FREE delivery Tue, Sep 24 Only 20 left in stock - order soon.',
       'FREE delivery Fri, Sep 27 Only 8 left in stock - order soon.',
       'FREE delivery Sep 23 - 24 Or fastest delivery Tomorrow, Sep 20',
       'FREE delivery Fri, Sep 27 Only 20 left in stock - order soon.',
       'FREE delivery Tomorrow, Sep 20 Only 5 left in stock - order soon.',
       'FREE delivery Sep 24 - 26 Or fastest delivery Mon, Sep 23',
       'FREE delivery Sep 23 - 25 Only 1 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Or fastest delivery Tomorrow, Sep 20 Only 2 left in stock - order soon.',
       'FREE delivery Mon, Sep 23 Only 1 left in stock - order soon.',
       'FREE delivery Tue, Sep 24 Only 13 left in stock - order soon.',
       'FREE delivery Fri, Sep 27 Or fastest delivery Mon, Sep 23',
       'FREE delivery Sat, Sep 21 Only 15 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Only 9 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Or fastest delivery Tomorrow, Sep 20 Only 7 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Only 3 left in stock - order soon.',
       'FREE delivery Thu, Sep 26 Or fastest delivery Tomorrow, Sep 20',
       'FREE deliveryOnly 1 left in stock - order soon.',
       'FREE delivery Thu, Sep 26 Only 10 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Or fastest delivery Tomorrow, Sep 20 Only 6 left in stock - order soon.',
       'FREE delivery Sep 24 - 25 Only 1 left in stock - order soon.',
       'FREE delivery Thu, Sep 26 Only 4 left in stock - order soon.',
       'FREE delivery Thu, Sep 26 Only 5 left in stock - order soon.',
       'FREE delivery Fri, Sep 27 on $35 of items shipped by Amazon',
       'FREE delivery Tue, Sep 24 Only 14 left in stock - order soon.',
       'FREE delivery Sep 24 - 26 Or fastest delivery Tomorrow, Sep 20 Only 3 left in stock - order soon.',
       'FREE delivery Thu, Sep 26 Or fastest delivery Tue, Sep 24 Only 13 left in stock (more on the way).',
       'FREE delivery Tue, Sep 24 Or fastest delivery Sat, Sep 21',
       'FREE delivery Tue, Sep 24 Only 16 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Only 13 left in stock - order soon.',
       'FREE delivery Thu, Sep 26 Or fastest delivery Tue, Sep 24',
       'FREE delivery Fri, Sep 27 Only 2 left in stock - order soon.',
       'FREE delivery Fri, Sep 27 Or fastest delivery Tomorrow, Sep 20 Only 19 left in stock - order soon.',
       'FREE delivery Tue, Sep 24 Only 11 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Only 2 left in stock - order soon.',
       'FREE delivery Sep 24 - 26 Or fastest delivery Sat, Sep 21 Only 2 left in stock - order soon.',
       'FREE delivery Sep 25 - 27 Or fastest delivery Tomorrow, Sep 20 Only 7 left in stock - order soon.',
       'FREE delivery Sep 25 - 27 Or fastest delivery Tomorrow, Sep 20 Only 1 left in stock - order soon.',
       'FREE delivery Tue, Sep 24 Only 18 left in stock - order soon.',
       'FREE delivery Tue, Sep 24 Only 5 left in stock - order soon.',
       'FREE delivery Sep 24 - 26 Or fastest delivery Sep 20 - 24',
       'FREE delivery Sep 26 - Oct 2 Or fastest delivery Tomorrow, Sep 20 Only 3 left in stock - order soon.',
       'FREE delivery Fri, Sep 27 Or fastest delivery Tomorrow, Sep 20',
       'FREE delivery Sep 23 - 25 Or fastest delivery Tomorrow, Sep 20',
       'FREE delivery Fri, Sep 27 Only 1 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Only 8 left in stock - order soon.',
       'FREE delivery Sep 24 - 26 Or fastest delivery Mon, Sep 23 Only 10 left in stock - order soon.',
       'FREE delivery Sat, Sep 21 Only 1 left in stock - order soon.',
       'FREE delivery Fri, Sep 27 Only 6 left in stock - order soon.',
       'FREE delivery Tue, Sep 24 Only 12 left in stock - order soon.',
       'FREE delivery Fri, Sep 27 Or fastest delivery Tomorrow, Sep 20 Only 6 left in stock - order soon.',
       'FREE delivery Wed, Sep 25 on $35 of items shipped by Amazon',
       'FREE delivery Tue, Sep 24 Only 19 left in stock - order soon.',
       'FREE delivery Thu, Sep 26 Only 13 left in stock - order soon.',
       'FREE delivery Mon, Sep 23',
       'FREE delivery Tue, Sep 24 Only 2 left in stock - order soon.',
       'FREE delivery Thu, Sep 26 Or fastest delivery Wed, Sep 25',
       'FREE delivery Sep 25 - 30'], dtype=object)

In [172]:
df[df['delivery'].str.contains("FREE", na=False)]

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,...,sales_volume,delivery,has_variations,unit_price,unit_count,coupon_text,clean_title,Brand,Product_Type,discount_percent
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.00,169.99,USD,4.0,1319,16,69.88,False,...,4K+ bought in past month,"FREE delivery Tue, Sep 24 Only 1 left in stock...",False,NaN,NaN,NaN,moto g play 2023 3 day battery unlocked made f...,Motorola,Smartphone,41.761280
1,B0CV2W1TKZ,"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RA...",153.99,153.99,USD,4.2,186,4,147.50,False,...,1K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,samsung galaxy a15 sm 155m/dsn 128gb 6gb ram d...,Samsung,Smartphone with bundle,0.000000
2,B09SM24S8C,"Samsung Galaxy A03s Cell Phone, AT&amp;T GSM U...",69.00,99.99,USD,3.8,597,35,64.99,False,...,2K+ bought in past month,"FREE delivery Tue, Sep 24",True,NaN,NaN,NaN,samsung galaxy a03s cell phone at&amp;t gsm un...,Samsung,Smartphone,30.993099
3,B0CHH1N9VY,TracFone | Motorola Moto g Pure | Locked | 32G...,49.99,49.99,USD,4.2,2814,3,43.99,False,...,500+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,tracfone motorola moto g pure locked 32gb 4000...,Motorola,Smartphone,0.000000
4,B09T3MQSVP,"Samsung Galaxy A13 5G Cell Phone, AT&amp;T GSM...",88.09,98.27,USD,3.8,1338,31,70.40,False,...,500+ bought in past month,"FREE delivery Mon, Sep 30",False,NaN,NaN,NaN,samsung galaxy a13 5g cell phone at&amp;t gsm ...,Samsung,Smartphone,10.359214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335,B0CZ3YPSRX,"Gimbal Stabilizer for Smartphone, 3-Axis Phone...",99.99,99.99,USD,4.7,8,1,99.99,False,...,Normal or Less then normal sales,"FREE delivery Thu, Sep 26",False,NaN,NaN,Save 50% with coupon,gimbal stabilizer for smartphone 3 axis phone ...,Not Famous brand,Smartphone,0.000000
336,B0CHB24KQJ,[True Military-Grade] Car Phone Holder【2024 St...,39.99,45.99,USD,4.4,2589,1,39.99,False,...,50+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,NaN,[true military grade] car phone holder【2024 st...,Not Famous brand,Holder,13.046314
337,B01LXOPZ4W,Wall Mount Cell Phone Charging Shelf | Multi-D...,273.00,273.00,USD,4.1,45,1,273.00,False,...,Normal or Less then normal sales,FREE delivery Sep 25 - 30,False,NaN,NaN,NaN,wall mount cell phone charging shelf multi dev...,Not Famous brand,Holder,0.000000
338,B0CXPJK7F7,"Sensyne 92&quot; Cell Phone Tripod, Selfie Sti...",29.99,29.99,USD,4.6,29066,1,29.99,True,...,300+ bought in past month,"FREE delivery Tue, Sep 24 on $35 of items ship...",False,NaN,NaN,NaN,sensyne 92&quot; cell phone tripod selfie stic...,Not Famous brand,Tripod,0.000000
339,B0CQ237PFS,Portable Charger 33800mAh USB C Power Bank wit...,45.95,69.95,USD,4.4,672,1,45.95,False,...,3K+ bought in past month,"FREE delivery Tue, Sep 24",False,NaN,NaN,Save 20% with coupon,portable charger 33800mah usb c power bank wit...,Not Famous brand,Charger,34.310222

In [173]:
# fill nans in  delivery column with "No delivery"
df['delivery'] = df['delivery'].fillna("No delivery")

In [174]:
## delevary column is not needed  becuse all delevary options are free and only 4 rows have no delivery so we will drop the column
df.drop('delivery', axis=1, inplace=True)

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_title                340 non-null    object
 2   product_price                340 non-null    float64
 3   product_original_price       340 non-null    float64
 4   currency                     336 non-null    object
 5   product_star_rating          340 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  340 non-null    float64
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         340 non-null    object
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 340 non-null    object
 15  has_variations               340 non-null    bool
 16  unit_price                   4 non-null      object
 17  unit_count                   4 non-null      float64
 18  coupon_text                  22 non-null     object
 19  clean_title                  340 non-null    object
 20  Brand                        340 non-null    object
 21  Product_Type                 340 non-null    object
 22  discount_percent             340 non-null    float64
dtypes: bool(5), float64(6), int64(2), object(10)
memory usage: 49.6+ KB

In [176]:
## nan in the unit price  and unite count column is more than 50% so we will drop the column
df.drop('unit_price', axis=1, inplace=True)
df.drop('unit_count', axis=1, inplace=True)

In [177]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_title                340 non-null    object
 2   product_price                340 non-null    float64
 3   product_original_price       340 non-null    float64
 4   currency                     336 non-null    object
 5   product_star_rating          340 non-null    float64
 6   product_num_ratings          340 non-null    int64
 7   product_num_offers           340 non-null    int64
 8   product_minimum_offer_price  340 non-null    float64
 9   is_best_seller               340 non-null    bool
 10  is_amazon_choice             340 non-null    bool
 11  is_prime                     340 non-null    bool
 12  product_availability         340 non-null    object
 13  climate_pledge_friendly      340 non-null    bool
 14  sales_volume                 340 non-null    object
 15  has_variations               340 non-null    bool
 16  coupon_text                  22 non-null     object
 17  clean_title                  340 non-null    object
 18  Brand                        340 non-null    object
 19  Product_Type                 340 non-null    object
 20  discount_percent             340 non-null    float64
dtypes: bool(5), float64(5), int64(2), object(9)
memory usage: 44.3+ KB

In [178]:
## Drop un useful columns
df.drop(columns=["coupon_text", "product_title", "currency"], inplace=True)

In [179]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         340 non-null    object
 1   product_price                340 non-null    float64
 2   product_original_price       340 non-null    float64
 3   product_star_rating          340 non-null    float64
 4   product_num_ratings          340 non-null    int64
 5   product_num_offers           340 non-null    int64
 6   product_minimum_offer_price  340 non-null    float64
 7   is_best_seller               340 non-null    bool
 8   is_amazon_choice             340 non-null    bool
 9   is_prime                     340 non-null    bool
 10  product_availability         340 non-null    object
 11  climate_pledge_friendly      340 non-null    bool
 12  sales_volume                 340 non-null    object
 13  has_variations               340 non-null    bool
 14  clean_title                  340 non-null    object
 15  Brand                        340 non-null    object
 16  Product_Type                 340 non-null    object
 17  discount_percent             340 non-null    float64
dtypes: bool(5), float64(5), int64(2), object(6)
memory usage: 36.3+ KB

## Data cleaning

remove dublicates

In [180]:
df.duplicated().sum()

np.int64(21)

In [181]:
df[df.duplicated()]

,asin,product_price,product_original_price,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,has_variations,clean_title,Brand,Product_Type,discount_percent
16,B0CV2W1TKZ,153.99,153.99,4.2,186,4,147.50,False,False,True,In Stock,False,1K+ bought in past month,False,samsung galaxy a15 sm 155m/dsn 128gb 6gb ram d...,Samsung,Smartphone with bundle,0.000000
18,B09SM24S8C,69.00,99.99,3.8,597,35,64.99,False,False,True,In Stock,False,2K+ bought in past month,True,samsung galaxy a03s cell phone at&amp;t gsm un...,Samsung,Smartphone,30.993099
19,B0CHH1N9VY,49.99,49.99,4.2,2814,3,43.99,False,False,True,In Stock,False,500+ bought in past month,False,tracfone motorola moto g pure locked 32gb 4000...,Motorola,Smartphone,0.000000
20,B0BZG14KFJ,49.99,59.99,4.4,3843,3,25.19,False,True,True,In Stock,False,4K+ bought in past month,False,panasonic cordless phone with answering machin...,Panasonic,Home Phone,16.669445
21,B0C2SWQBMB,149.99,249.99,4.2,2637,8,100.72,False,False,True,In Stock,False,2K+ bought in past month,True,motorola moto g 5g 2023 unlocked made for us 4...,Motorola,Smartphone,40.001600
22,B0CTD47P22,149.50,158.00,4.2,253,9,146.50,False,False,True,In Stock,False,500+ bought in past month,False,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung,Smartphone,5.379747
23,B0CSB14R7J,139.99,139.99,4.3,573,15,136.62,False,False,True,In Stock,False,1K+ bought in past month,False,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung,Smartphone,0.000000
24,B0CHK6LWKZ,59.99,59.99,4.0,258,4,50.48,False,False,True,In Stock,False,1K+ bought in past month,False,tracfone samsung galaxy a03s locked 32gb 5000m...,Samsung,Smartphone,0.000000
25,B0C5BMB1WB,89.00,89.00,4.0,204,10,85.44,False,False,True,In Stock,False,1K+ bought in past month,False,motorola one ace 2021 2 day battery unlocked m...,Motorola,Smartphone,0.000000
27,B0CN1QSH8Q,199.99,199.99,4.0,610,2,154.00,False,False,True,In Stock,True,2K+ bought in past month,True,samsung galaxy a15 5g a series cell phone 128g...,Samsung,Smartphone,0.000000
28,B0C22BRGLG,249.99,299.99,4.3,963,5,209.28,False,False,True,In Stock,False,1K+ bought in past month,False,oneplus nord n30 5g unlocked dual sim android ...,OnePlus,Smartphone,16.667222
29,B09NZQJRN7,18.45,18.45,4.3,9096,2,13.84,False,False,True,In Stock,False,2K+ bought in past month,False,vtech dect 6.0 cordless phone blue display big...,VTech,Home Phone,0.000000
73,B09LKXHWCF,355.81,415.00,4.1,4265,20,303.99,False,False,False,In Stock,True,500+ bought in past month,True,apple iphone 13 mini 128gb blue unlocked renewed,Apple,iPhone,14.262651
131,B0B8F1S1XG,51.60,65.95,4.3,574,6,27.67,False,False,True,In Stock,False,500+ bought in past month,False,at&amp;t cl82219 dect 6.0 2 handset cordless p...,Not Famous brand,Home Phone,21.758908
133,B096YK3RN9,246.00,246.00,4.0,1340,21,187.00,False,False,False,Only 5 left in stock - order soon.,True,100+ bought in past month,True,samsung galaxy s21+ plus g996u fully unlocked ...,Samsung,Smartphone,0.000000
134,B0DB88HK1Z,99.99,119.99,2.8,6,1,99.99,False,False,True,In Stock,False,List:,True,reno 11 pro unlocked android phone 6.7 inch hd...,Not Famous brand,Smartphone,16.668056
136,B0BHHJV7W9,117.77,117.77,4.3,20608,4,57.19,False,False,True,In Stock,False,500+ bought in past month,False,at&amp;t cl82507 dect 6.0 5 handset cordless p...,Not Famous brand,Home Phone,0.000000
137,B0BTTQGVVW,64.94,64.94,3.9,1492,9,49.90,False,False,False,In Stock,False,1K+ bought in past month,False,cat s22 flip 16gb 2.8&quot; touchscreen androi...,Not Famous brand,Flip Phone,0.000000
310,B0B4F4DH6H,114.28,129.99,4.2,539,2,41.84,False,False,True,In Stock,False,50+ bought in past month,False,panasonic expandable corded phone system bluet...,Panasonic,Home Phone,12.085545
311,B0D6Z95D5K,119.99,119.99,5.0,1,1,119.99,False,False,True,In Stock,False,Normal or Less then normal sales,True,motorola moto g04 xt2421 2 dual sim factory gs...,Motorola,Smartphone,0.000000
312,B0C9LPCS42,689.99,689.99,4.5,224,6,640.28,False,False,False,In Stock,False,More Buying Choices,True,nothing phone 2 512 gb + 12 gb ram glyph inter...,Not Famous brand,Smartphone,0.000000

In [182]:
df.duplicated(subset=["asin"]).sum()

np.int64(25)

In [183]:
df["clean_title"].duplicated().sum()

np.int64(25)

In [184]:
df[df["asin"].duplicated()]

,asin,product_price,product_original_price,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,has_variations,clean_title,Brand,Product_Type,discount_percent
16,B0CV2W1TKZ,153.99,153.99,4.2,186,4,147.50,False,False,True,In Stock,False,1K+ bought in past month,False,samsung galaxy a15 sm 155m/dsn 128gb 6gb ram d...,Samsung,Smartphone with bundle,0.000000
17,B0BQ118F2T,99.00,169.99,4.0,1319,16,69.88,False,False,True,Only 3 left in stock - order soon.,False,4K+ bought in past month,False,moto g play 2023 3 day battery unlocked made f...,Motorola,Smartphone,41.761280
18,B09SM24S8C,69.00,99.99,3.8,597,35,64.99,False,False,True,In Stock,False,2K+ bought in past month,True,samsung galaxy a03s cell phone at&amp;t gsm un...,Samsung,Smartphone,30.993099
19,B0CHH1N9VY,49.99,49.99,4.2,2814,3,43.99,False,False,True,In Stock,False,500+ bought in past month,False,tracfone motorola moto g pure locked 32gb 4000...,Motorola,Smartphone,0.000000
20,B0BZG14KFJ,49.99,59.99,4.4,3843,3,25.19,False,True,True,In Stock,False,4K+ bought in past month,False,panasonic cordless phone with answering machin...,Panasonic,Home Phone,16.669445
21,B0C2SWQBMB,149.99,249.99,4.2,2637,8,100.72,False,False,True,In Stock,False,2K+ bought in past month,True,motorola moto g 5g 2023 unlocked made for us 4...,Motorola,Smartphone,40.001600
22,B0CTD47P22,149.50,158.00,4.2,253,9,146.50,False,False,True,In Stock,False,500+ bought in past month,False,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung,Smartphone,5.379747
23,B0CSB14R7J,139.99,139.99,4.3,573,15,136.62,False,False,True,In Stock,False,1K+ bought in past month,False,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung,Smartphone,0.000000
24,B0CHK6LWKZ,59.99,59.99,4.0,258,4,50.48,False,False,True,In Stock,False,1K+ bought in past month,False,tracfone samsung galaxy a03s locked 32gb 5000m...,Samsung,Smartphone,0.000000
25,B0C5BMB1WB,89.00,89.00,4.0,204,10,85.44,False,False,True,In Stock,False,1K+ bought in past month,False,motorola one ace 2021 2 day battery unlocked m...,Motorola,Smartphone,0.000000
26,B0CRVWPWKP,194.99,194.99,4.0,259,15,164.50,False,False,True,In Stock,False,400+ bought in past month,True,samsung galaxy a25 5g a256e 128gb dual sim gsm...,Samsung,Smartphone,0.000000
27,B0CN1QSH8Q,199.99,199.99,4.0,610,2,154.00,False,False,True,In Stock,True,2K+ bought in past month,True,samsung galaxy a15 5g a series cell phone 128g...,Samsung,Smartphone,0.000000
28,B0C22BRGLG,249.99,299.99,4.3,963,5,209.28,False,False,True,In Stock,False,1K+ bought in past month,False,oneplus nord n30 5g unlocked dual sim android ...,OnePlus,Smartphone,16.667222
29,B09NZQJRN7,18.45,18.45,4.3,9096,2,13.84,False,False,True,In Stock,False,2K+ bought in past month,False,vtech dect 6.0 cordless phone blue display big...,VTech,Home Phone,0.000000
56,B09T3MQSVP,88.82,98.27,3.8,1338,31,70.40,False,False,False,Only 1 left in stock - order soon.,False,500+ bought in past month,False,samsung galaxy a13 5g cell phone at&amp;t gsm ...,Samsung,Smartphone,9.616363
73,B09LKXHWCF,355.81,415.00,4.1,4265,20,303.99,False,False,False,In Stock,True,500+ bought in past month,True,apple iphone 13 mini 128gb blue unlocked renewed,Apple,iPhone,14.262651
131,B0B8F1S1XG,51.60,65.95,4.3,574,6,27.67,False,False,True,In Stock,False,500+ bought in past month,False,at&amp;t cl82219 dect 6.0 2 handset cordless p...,Not Famous brand,Home Phone,21.758908
133,B096YK3RN9,246.00,246.00,4.0,1340,21,187.00,False,False,False,Only 5 left in stock - order soon.,True,100+ bought in past month,True,samsung galaxy s21+ plus g996u fully unlocked ...,Samsung,Smartphone,0.000000
134,B0DB88HK1Z,99.99,119.99,2.8,6,1,99.99,False,False,True,In Stock,False,List:,True,reno 11 pro unlocked android phone 6.7 inch hd...,Not Famous brand,Smartphone,16.668056
136,B0BHHJV7W9,117.77,117.77,4.3,20608,4,57.19,False,False,True,In Stock,False,500+ bought in past month,False,at&amp;t cl82507 dect 6.0 5 handset cordless p...,Not Famous brand,Home Phone,0.000000
137,B0BTTQGVVW,64.94,64.94,3.9,1492,9,49.90,False,False,False,In Stock,False,1K+ bought in past month,False,cat s22 flip 16gb 2.8&quot; touchscreen androi...,Not Famous brand,Flip Phone,0.000000
212,B0CMDRFVTL,859.99,859.99,4.4,424,1,859.99,False,False,True,In Stock,True,100+ bought in past month,False,samsung galaxy s24 cell phone 256gb ai smartph...,Samsung,Smartphone,0.000000
310,B0B4F4DH6H,114.28,129.99,4.2,539,2,41.84,False,False,True,In Stock,False,50+ bought in past month,False,panasonic expandable corded phone system bluet...,Panasonic,Home Phone,12.085545
311,B0D6Z95D5K,119.99,119.99,5.0,1,1,119.99,False,False,True,In Stock,False,Normal or Less then normal sales,True,motorola moto g04 xt2421 2 dual sim factory gs...,Motorola,Smartphone,0.000000
312,B0C9LPCS42,689.99,689.99,4.5,224,6,640.28,False,False,False,In Stock,False,More Buying Choices,True,nothing phone 2 512 gb + 12 gb ram glyph inter...,Not Famous brand,Smartphone,0.000000

In [185]:
all_duplicates = df[df.duplicated(subset=['asin'], keep=False)]
all_duplicates_sorted = all_duplicates.sort_values(by='asin')
all_duplicates_sorted

,asin,product_price,product_original_price,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,has_variations,clean_title,Brand,Product_Type,discount_percent
126,B096YK3RN9,246.00,246.00,4.0,1340,21,187.00,False,False,False,Only 5 left in stock - order soon.,True,100+ bought in past month,True,samsung galaxy s21+ plus g996u fully unlocked ...,Samsung,Smartphone,0.000000
133,B096YK3RN9,246.00,246.00,4.0,1340,21,187.00,False,False,False,Only 5 left in stock - order soon.,True,100+ bought in past month,True,samsung galaxy s21+ plus g996u fully unlocked ...,Samsung,Smartphone,0.000000
15,B09LKXHWCF,355.81,415.00,4.1,4265,20,303.99,False,False,False,In Stock,True,500+ bought in past month,True,apple iphone 13 mini 128gb blue unlocked renewed,Apple,iPhone,14.262651
73,B09LKXHWCF,355.81,415.00,4.1,4265,20,303.99,False,False,False,In Stock,True,500+ bought in past month,True,apple iphone 13 mini 128gb blue unlocked renewed,Apple,iPhone,14.262651
29,B09NZQJRN7,18.45,18.45,4.3,9096,2,13.84,False,False,True,In Stock,False,2K+ bought in past month,False,vtech dect 6.0 cordless phone blue display big...,VTech,Home Phone,0.000000
14,B09NZQJRN7,18.45,18.45,4.3,9096,2,13.84,False,False,True,In Stock,False,2K+ bought in past month,False,vtech dect 6.0 cordless phone blue display big...,VTech,Home Phone,0.000000
18,B09SM24S8C,69.00,99.99,3.8,597,35,64.99,False,False,True,In Stock,False,2K+ bought in past month,True,samsung galaxy a03s cell phone at&amp;t gsm un...,Samsung,Smartphone,30.993099
2,B09SM24S8C,69.00,99.99,3.8,597,35,64.99,False,False,True,In Stock,False,2K+ bought in past month,True,samsung galaxy a03s cell phone at&amp;t gsm un...,Samsung,Smartphone,30.993099
56,B09T3MQSVP,88.82,98.27,3.8,1338,31,70.40,False,False,False,Only 1 left in stock - order soon.,False,500+ bought in past month,False,samsung galaxy a13 5g cell phone at&amp;t gsm ...,Samsung,Smartphone,9.616363
4,B09T3MQSVP,88.09,98.27,3.8,1338,31,70.40,False,False,True,In Stock,False,500+ bought in past month,False,samsung galaxy a13 5g cell phone at&amp;t gsm ...,Samsung,Smartphone,10.359214
307,B0B4F4DH6H,114.28,129.99,4.2,539,2,41.84,False,False,True,In Stock,False,50+ bought in past month,False,panasonic expandable corded phone system bluet...,Panasonic,Home Phone,12.085545
310,B0B4F4DH6H,114.28,129.99,4.2,539,2,41.84,False,False,True,In Stock,False,50+ bought in past month,False,panasonic expandable corded phone system bluet...,Panasonic,Home Phone,12.085545
123,B0B8F1S1XG,51.60,65.95,4.3,574,6,27.67,False,False,True,In Stock,False,500+ bought in past month,False,at&amp;t cl82219 dect 6.0 2 handset cordless p...,Not Famous brand,Home Phone,21.758908
131,B0B8F1S1XG,51.60,65.95,4.3,574,6,27.67,False,False,True,In Stock,False,500+ bought in past month,False,at&amp;t cl82219 dect 6.0 2 handset cordless p...,Not Famous brand,Home Phone,21.758908
136,B0BHHJV7W9,117.77,117.77,4.3,20608,4,57.19,False,False,True,In Stock,False,500+ bought in past month,False,at&amp;t cl82507 dect 6.0 5 handset cordless p...,Not Famous brand,Home Phone,0.000000
128,B0BHHJV7W9,117.77,117.77,4.3,20608,4,57.19,False,False,True,In Stock,False,500+ bought in past month,False,at&amp;t cl82507 dect 6.0 5 handset cordless p...,Not Famous brand,Home Phone,0.000000
17,B0BQ118F2T,99.00,169.99,4.0,1319,16,69.88,False,False,True,Only 3 left in stock - order soon.,False,4K+ bought in past month,False,moto g play 2023 3 day battery unlocked made f...,Motorola,Smartphone,41.761280
0,B0BQ118F2T,99.00,169.99,4.0,1319,16,69.88,False,False,True,Only 1 left in stock - order soon.,False,4K+ bought in past month,False,moto g play 2023 3 day battery unlocked made f...,Motorola,Smartphone,41.761280
127,B0BTTQGVVW,64.94,64.94,3.9,1492,9,49.90,False,False,False,In Stock,False,1K+ bought in past month,False,cat s22 flip 16gb 2.8&quot; touchscreen androi...,Not Famous brand,Flip Phone,0.000000
137,B0BTTQGVVW,64.94,64.94,3.9,1492,9,49.90,False,False,False,In Stock,False,1K+ bought in past month,False,cat s22 flip 16gb 2.8&quot; touchscreen androi...,Not Famous brand,Flip Phone,0.000000
20,B0BZG14KFJ,49.99,59.99,4.4,3843,3,25.19,False,True,True,In Stock,False,4K+ bought in past month,False,panasonic cordless phone with answering machin...,Panasonic,Home Phone,16.669445
5,B0BZG14KFJ,49.99,59.99,4.4,3843,3,25.19,False,True,True,In Stock,False,4K+ bought in past month,False,panasonic cordless phone with answering machin...,Panasonic,Home Phone,16.669445
13,B0C22BRGLG,249.99,299.99,4.3,963,5,209.28,False,False,True,In Stock,False,1K+ bought in past month,False,oneplus nord n30 5g unlocked dual sim android ...,OnePlus,Smartphone,16.667222
28,B0C22BRGLG,249.99,299.99,4.3,963,5,209.28,False,False,True,In Stock,False,1K+ bought in past month,False,oneplus nord n30 5g unlocked dual sim android ...,OnePlus,Smartphone,16.667222
21,B0C2SWQBMB,149.99,249.99,4.2,2637,8,100.72,False,False,True,In Stock,False,2K+ bought in past month,True,motorola moto g 5g 2023 unlocked made for us 4...,Motorola,Smartphone,40.001600
6,B0C2SWQBMB,149.99,249.99,4.2,2637,8,100.72,False,False,True,In Stock,False,2K+ bought in past month,True,motorola moto g 5g 2023 unlocked made for us 4...,Motorola,Smartphone,40.001600
10,B0C5BMB1WB,89.00,89.00,4.0,204,10,85.44,False,False,True,In Stock,False,1K+ bought in past month,False,motorola one ace 2021 2 day battery unlocked m...,Motorola,Smartphone,0.000000
25,B0C5BMB1WB,89.00,89.00,4.0,204,10,85.44,False,False,True,In Stock,False,1K+ bought in past month,False,motorola one ace 2021 2 day battery unlocked m...,Motorola,Smartphone,0.000000
309,B0C9LPCS42,689.99,689.99,4.5,224,6,640.28,False,False,False,In Stock,False,More Buying Choices,True,nothing phone 2 512 gb + 12 gb ram glyph inter...,Not Famous brand,Smartphone,0.000000
312,B0C9LPCS42,689.99,689.99,4.5,224,6,640.28,False,False,False,In Stock,False,More Buying Choices,True,nothing phone 2 512 gb + 12 gb ram glyph inter...,Not Famous brand,Smartphone,0.000000
3,B0CHH1N9VY,49.99,49.99,4.2,2814,3,43.99,False,False,True,In Stock,False,500+ bought in past month,False,tracfone motorola moto g pure locked 32gb 4000...,Motorola,Smartphone,0.000000
19,B0CHH1N9VY,49.99,49.99,4.2,2814,3,43.99,False,False,True,In Stock,False,500+ bought in past month,False,tracfone motorola moto g pure locked 32gb 4000...,Motorola,Smartphone,0.000000
24,B0CHK6LWKZ,59.99,59.99,4.0,258,4,50.48,False,False,True,In Stock,False,1K+ bought in past month,False,tracfone samsung galaxy a03s locked 32gb 5000m...,Samsung,Smartphone,0.000000
9,B0CHK6LWKZ,59.99,59.99,4.0,258,4,50.48,False,False,True,In Stock,False,1K+ bought in past month,False,tracfone samsung galaxy a03s locked 32gb 5000m...,Samsung,Smartphone,0.000000
97,B0CMDRFVTL,859.99,859.99,4.4,424,2,724.02,False,False,True,In Stock,True,100+ bought in past month,True,samsung galaxy s24 cell phone 256gb ai smartph...,Samsung,Smartphone,0.000000
212,B0CMDRFVTL,859.99,859.99,4.4,424,1,859.99,False,False,True,In Stock,True,100+ bought in past month,False,samsung galaxy s24 cell phone 256gb ai smartph...,Samsung,Smartphone,0.000000
27,B0CN1QSH8Q,199.99,199.99,4.0,610,2,154.00,False,False,True,In Stock,True,2K+ bought in past month,True,samsung galaxy a15 5g a series cell phone 128g...,Samsung,Smartphone,0.000000
12,B0CN1QSH8Q,199.99,199.99,4.0,610,2,154.00,False,False,True,In Stock,True,2K+ bought in past month,True,samsung galaxy a15 5g a series cell phone 128g...,Samsung,Smartphone,0.000000
26,B0CRVWPWKP,194.99,194.99,4.0,259,15,164.50,False,False,True,In Stock,False,400+ bought in past month,True,samsung galaxy a25 5g a256e 128gb dual sim gsm...,Samsung,Smartphone,0.000000
11,B0CRVWPWKP,195.00,195.00,4.0,259,15,164.50,False,False,True,In Stock,False,400+ bought in past month,True,samsung galaxy a25 5g a256e 128gb dual sim gsm...,Samsung,Smartphone,0.000000
8,B0CSB14R7J,139.99,139.99,4.3,573,15,136.62,False,False,True,In Stock,False,1K+ bought in past month,False,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung,Smartphone,0.000000
23,B0CSB14R7J,139.99,139.99,4.3,573,15,136.62,False,False,True,In Stock,False,1K+ bought in past month,False,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung,Smartphone,0.000000
22,B0CTD47P22,149.50,158.00,4.2,253,9,146.50,False,False,True,In Stock,False,500+ bought in past month,False,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung,Smartphone,5.379747
7,B0CTD47P22,149.50,158.00,4.2,253,9,146.50,False,False,True,In Stock,False,500+ bought in past month,False,samsung galaxy a15 a155m 128gb dual sim gsm un...,Samsung,Smartphone,5.379747
16,B0CV2W1TKZ,153.99,153.99,4.2,186,4,147.50,False,False,True,In Stock,False,1K+ bought in past month,False,samsung galaxy a15 sm 155m/dsn 128gb 6gb ram d...,Samsung,Smartphone with bundle,0.000000
1,B0CV2W1TKZ,153.99,153.99,4.2,186,4,147.50,False,False,True,In Stock,False,1K+ bought in past month,False,samsung galaxy a15 sm 155m/dsn 128gb 6gb ram d...,Samsung,Smartphone with bundle,0.000000
308,B0D6Z95D5K,119.99,119.99,5.0,1,1,119.99,False,False,True,In Stock,False,Normal or Less then normal sales,True,motorola moto g04 xt2421 2 dual sim factory gs...,Motorola,Smartphone,0.000000
311,B0D6Z95D5K,119.99,119.99,5.0,1,1,119.99,False,False,True,In Stock,False,Normal or Less then normal sales,True,motorola moto g04 xt2421 2 dual sim factory gs...,Motorola,Smartphone,0.000000
134,B0DB88HK1Z,99.99,119.99,2.8,6,1,99.99,False,False,True,In Stock,False,List:,True,reno 11 pro unlocked android phone 6.7 inch hd...,Not Famous brand,Smartphone,16.668056
129,B0DB88HK1Z,99.99,119.99,2.8,6,1,99.99,False,False,True,In Stock,False,List:,True,reno 11 pro unlocked android phone 6.7 inch hd...,Not Famous brand,Smartphone,16.668056

In [186]:
## kepping the first occurrence of each duplicate and dropping the rest
df = df.drop_duplicates(subset=['asin'], keep='first')

In [187]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 315 entries, 0 to 339
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         315 non-null    object
 1   product_price                315 non-null    float64
 2   product_original_price       315 non-null    float64
 3   product_star_rating          315 non-null    float64
 4   product_num_ratings          315 non-null    int64
 5   product_num_offers           315 non-null    int64
 6   product_minimum_offer_price  315 non-null    float64
 7   is_best_seller               315 non-null    bool
 8   is_amazon_choice             315 non-null    bool
 9   is_prime                     315 non-null    bool
 10  product_availability         315 non-null    object
 11  climate_pledge_friendly      315 non-null    bool
 12  sales_volume                 315 non-null    object
 13  has_variations               315 non-null    bool
 14  clean_title                  315 non-null    object
 15  Brand                        315 non-null    object
 16  Product_Type                 315 non-null    object
 17  discount_percent             315 non-null    float64
dtypes: bool(5), float64(5), int64(2), object(6)
memory usage: 36.0+ KB

remove outliers

In [188]:
## Exprloring the data cleaning and preprocessing steps
q1 = df['product_price'].quantile(0.25)
q3 = df['product_price'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
outliers = df[(df['product_price'] < lower_bound) | (df['product_price'] > upper_bound)]

In [189]:
outliers.shape

(23, 18)

In [190]:
outliers

,asin,product_price,product_original_price,product_star_rating,product_num_ratings,product_num_offers,product_minimum_offer_price,is_best_seller,is_amazon_choice,is_prime,product_availability,climate_pledge_friendly,sales_volume,has_variations,clean_title,Brand,Product_Type,discount_percent
32,B0CMDL3H3V,798.00,999.99,4.5,615,2,741.99,False,False,True,In Stock,True,1K+ bought in past month,True,samsung galaxy s24+ plus cell phone 256gb ai s...,Samsung,Smartphone,20.199202
36,B0CD99XXQY,499.99,599.99,4.5,1159,2,451.19,False,False,True,In Stock,True,200+ bought in past month,True,samsung galaxy s23 fe ai phone 128gb unlocked ...,Samsung,Smartphone,16.666944
50,B0CLHJZJZB,479.72,479.72,4.3,39,3,429.50,False,False,False,Only 1 left in stock - order soon.,False,50+ bought in past month,False,samsung galaxy s23 fan edition fe 5g sm s711b/...,Samsung,Smartphone,0.000000
55,B0CGWF3F64,699.99,699.99,4.0,440,2,331.64,False,False,True,In Stock,False,200+ bought in past month,True,motorola razr 2023 unlocked made for us 8/128 ...,Motorola,Smartphone,0.000000
67,B09LNT1F3H,422.00,422.00,4.1,12051,29,305.96,False,False,False,In Stock,True,500+ bought in past month,True,apple iphone 13 128gb red unlocked renewed,Apple,iPhone,0.000000
72,B0BV5SV5HL,799.99,859.99,4.4,380,11,759.50,False,False,False,In Stock,False,400+ bought in past month,False,samsung galaxy s23 ultra 5g sm s918b/ds dual s...,Samsung,Smartphone,6.976825
77,B0CQ9SZJN6,549.99,599.99,4.4,397,2,493.11,False,False,True,In Stock,False,400+ bought in past month,True,oneplus 12r 16gb ram+256gb dual sim us factory...,OnePlus,Smartphone,8.333472
97,B0CMDRFVTL,859.99,859.99,4.4,424,2,724.02,False,False,True,In Stock,True,100+ bought in past month,True,samsung galaxy s24 cell phone 256gb ai smartph...,Samsung,Smartphone,0.000000
102,B0CQ5JGH2Y,799.99,899.99,4.5,506,2,715.67,False,False,True,In Stock,False,400+ bought in past month,False,oneplus 12 16gb ram+512gb dual sim unlocked an...,OnePlus,Smartphone,11.111235
120,B0CGTKM9WC,499.00,699.00,4.3,2391,5,475.00,False,False,True,In Stock,True,400+ bought in past month,True,google pixel 8 unlocked android smartphone wit...,Pixel,Smartphone,28.612303
124,B0CD8YMKWC,559.99,659.99,4.5,1159,2,451.85,False,False,True,In Stock,True,100+ bought in past month,True,samsung galaxy s23 fe cell phone 256gb unlocke...,Samsung,Smartphone,15.151745
143,B08PMP778K,469.99,469.99,4.2,9355,8,449.99,False,False,True,Only 2 left in stock - order soon.,True,400+ bought in past month,True,apple iphone 12 pro max 128gb pacific blue ful...,Apple,iPhone,0.000000
150,B0D18SMB1X,1614.99,2019.99,4.1,83,10,1583.65,False,False,False,Only 5 left in stock - order soon.,True,300+ bought in past month,True,samsung galaxy z fold 6 ai cell phone 512gb un...,Samsung,Smartphone,20.049604
151,B0BCQXY9H8,499.95,499.95,4.2,2755,4,485.00,False,False,True,In Stock,True,50+ bought in past month,True,google pixel 7 pro 5g android phone unlocked s...,Pixel,Smartphone,0.000000
176,B0CMPLN52T,620.05,661.99,4.4,566,21,615.99,False,False,False,Only 1 left in stock - order soon.,False,200+ bought in past month,True,apple iphone 15 128gb pink unlocked renewed,Apple,iPhone,6.335443
194,B0CMDKX76Q,859.99,859.99,4.4,424,1,859.99,False,False,True,In Stock,True,50+ bought in past month,False,samsung galaxy s24 cell phone 256gb ai smartph...,Samsung,Smartphone,0.000000
197,B0CHN7M531,1299.99,1699.99,4.1,218,4,1138.07,False,False,True,In Stock,False,200+ bought in past month,True,oneplus open 16gb ram+512gb dual sim voyager b...,OnePlus,Smartphone,23.529550
199,B0CLHHNWZQ,473.50,473.50,4.2,99,1,473.50,False,False,False,Only 3 left in stock - order soon.,False,50+ bought in past month,True,samsung galaxy s23 fe s711b 256gb dual sim gsm...,Samsung,Smartphone,0.000000
235,B0D19B2D19,944.96,1219.99,4.2,93,8,899.99,False,False,False,In Stock,True,300+ bought in past month,True,samsung galaxy z flip 6 ai cell phone 512gb un...,Samsung,Flip Phone,22.543627
281,B0BYL93774,541.06,579.00,4.2,776,6,511.67,False,False,True,In Stock,False,500+ bought in past month,True,apple iphone 14 128gb midnight unlocked renewe...,Apple,iPhone,6.552677
309,B0C9LPCS42,689.99,689.99,4.5,224,6,640.28,False,False,False,In Stock,False,More Buying Choices,True,nothing phone 2 512 gb + 12 gb ram glyph inter...,Not Famous brand,Smartphone,0.000000
315,B0D7HWR5QG,1199.00,1199.00,4.3,41,3,1151.04,False,False,True,In Stock,False,300+ bought in past month,False,google pixel 9 pro xl unlocked android smartph...,Pixel,Smartphone,0.000000
316,B0CV73SG4Z,993.90,993.90,4.3,43,1,993.90,False,False,False,In Stock,False,200+ bought in past month,False,samsung galaxy s24 ultra 5g s9280 physical dua...,Samsung,Smartphone,0.000000

Final decision no outliers

In [191]:
## Re indexing the dataframe after dropping duplicates
df.reset_index(drop=True, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   asin                         315 non-null    object
 1   product_price                315 non-null    float64
 2   product_original_price       315 non-null    float64
 3   product_star_rating          315 non-null    float64
 4   product_num_ratings          315 non-null    int64
 5   product_num_offers           315 non-null    int64
 6   product_minimum_offer_price  315 non-null    float64
 7   is_best_seller               315 non-null    bool
 8   is_amazon_choice             315 non-null    bool
 9   is_prime                     315 non-null    bool
 10  product_availability         315 non-null    object
 11  climate_pledge_friendly      315 non-null    bool
 12  sales_volume                 315 non-null    object
 13  has_variations               315 non-null    bool
 14  clean_title                  315 non-null    object
 15  Brand                        315 non-null    object
 16  Product_Type                 315 non-null    object
 17  discount_percent             315 non-null    float64
dtypes: bool(5), float64(5), int64(2), object(6)
memory usage: 33.7+ KB

In [192]:
## Save the cleaned dataset to a new CSV file
df.to_csv(r"C:\Users\mohsa\OneDrive\Desktop\AMIT Final Project\cleaned_phone_search.csv", index=False)